### ISSUE TITLE
Accordion Content Shift in Safari

### ISSUE THREAD

**Issue by niktek** [skeletonlabs/skeleton#1007]
### Current Behavior

When opening an AccordionItem in Safari the content underneath shifts up and down a bit at the end of the animation

**Comment by endigo9740** [comment]
@niktek I took a look at this, I can recreate the issue (the wobble) but I feel this may reside on Svelte's end:
https://github.com/sveltejs/svelte/issues/4712

> Another way I found it useful to do this on safari (without adding css property) is don't use built-in slide function with transition directive in Safari since it uses css animation. Safari has a bug that it'll ignore element overflow: hidden when element is transitioning.

They mention a work around later in that thread, and even that it was fixed in a release. But nothing I've thrown at this seems to help. I'm going to mark this "help wanted" in case anyone else wants to take a look.

**Comment by endigo9740** [comment]
I'm going to say for now this is something we cannot actually solve on our end. I feel the fault lies within Svelte transition slide and Safari. I might suggest reporting this upstream if you get a chance @niktek
