### ISSUE TITLE
Support for mobile safe area

### ISSUE THREAD

**Issue by saostad** [skeletonlabs/skeleton#1036]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Hi Guys, 

Currently, there is no support for the mobile safe area in Skeleton. 
I saw some solutions but don't know which one is better.
Here is an article from [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/env).

![safe-area-layout-guide-iOS-notch-iphonex](https://user-images.githubusercontent.com/16025625/221259842-1a8001e8-39c5-4afb-9beb-1b4679bab541.jpg)

Thanks.

### What type of pull request would this be?

None

### Any links to similar examples or other references we should review?

- [Konstaui](https://konstaui.com/svelte/safe-areas)
- [css-tricks](https://css-tricks.com/custom-tailwind-css/)

**Comment by saostad** [comment]
@endigo9740  is there anything I can do to help on this issue?

**Comment by endigo9740** [comment]
@saostad Probably not right now, this will take an extensive amount of effort to look into supporting. It may affect a number of features within Skeleton. Our current priorities are focused on documentation updates, leading to our v1 launch. Given this, I wouldn't expect to see any movement on this until after that at the earliest.

**Comment by endigo9740** [comment]
After further review of this issue, I think a lot of this is based around layout. We provide our App Shell as a one potential way to handle app layouts, but users are completely at liberty to create their own custom layouts if their applications would benefit. Given this is the only issue that's ever been raised on this topic in the 9 months since the project went open source, I think we can safely mark this as a non-issue for most users.

If someone comes across this ticket and is looking for a solution, my recommendation is building your own mobile-safe layout for your application.
