### ISSUE TITLE
Transitions

### ISSUE THREAD

**Issue by cycle4passion** [skeletonlabs/skeleton#1093]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

It seems like all the components should have exposed transitions props just like you exposing actions. You could have transition/option for combined in/out, as well as individual in/options and out/options.

### What type of pull request would this be?

None

**Comment by endigo9740** [comment]
@cycle4passion unfortunately Svelte transitions and Actions are not apt comparisons here.

Let's take the Avatar component for example, we accept the following props:

```ts
export let action: any = () => {};
export let actionParams = '';
```

- `action` represents the actual action function to run
- `actionParams` represent the object of optional settings (aka `args`) to said action

Then within the component we use the following to apply the action to the `img` element:

```html
<img ... use:action={actionParams} />
```

This works great for Actions. However, if we take a look at even a minimal example of a Svelte transition we'll notice some key differences. 

https://svelte.dev/tutorial/transition

```html
<script>
	import { fade } from 'svelte/transition';
	let visible = true;
</script>

<label>
	<input type="checkbox" bind:checked={visible}>
	visible
</label>
{#if visible}
	<p transition:fade>Fades in and out</p>
{/if}
```

The good news is I tested the transition directive of `transition:foo` where `foo` was an empty object, and it did work as expected. So that's good, at least it's somewhat comparable there.

However, a key difference with Svelte Transitions is they require a wrapping`{#if}` statement around the element that contains the transition directive (ex: `transition:foo`). This means we would need a THIRD prop added that's a boolean value.

So what I'm saying, is that while there's some technical capabilities to do this. It's not going to be be a trivial lift to implement. And there's a bit of the elephant in the room here, in that there's nothing stopping you from implementing this using a wrapping element instead. It would work exactly the same for zero additional effort. Here's a quick trivial example:

```html
<script>
	import { fade } from 'svelte/transition';
	let visible = true;
</script>

<label>
	<input type="checkbox" bind:checked={visible}>
	visible
</label>
{#if visible}
	<div transition:fade>
                <Avatar src="https://i.pravatar.cc/?img=48" width="w-32" />
        </div>
{/if}
```

My guess is that's not what you want though, that you want localized transitions within a portion of the component. And that complicates things ten fold. We then have to have a matching set of transition function, transition params, and boolean conditions PER portion of the component that's being transitions. All in all I just don't feel that's a reasonable ask.

What I might suggest instead, is let us know if there are particular components that you would like to see containing a built-in animation feature. For example, folks asked for Accordions to animate when open/closing AccordionItems. We'll gladly field requests like that. And honestly it may be a better approach since it benefits everyone.

**Comment by endigo9740** [comment]
> Thank you for your very well thought out and considerate response. I have to agree with you. To further add to your argument, people would probably want transition   in: and out: options further increasing the params count. I agree that a wrapping conditional div is probably the best solution.

For sure, it could get real messy, real quick.

> I guess the component I was thinking about and prompting my request was tabs.    This surely need transition support when tabpanels   change. I think this warrants the special special   use case as you did for accordion. For accordion a slide up/down is obvious.    For a tabpanel change either fade or     slide left/right (not natively supported by svelte transitions) would seem to the most obvious.

Great suggestion. Would you mind setting up a feature request for that? Obviously our focus right now is the v1.0 launch later this week, but I feel like this is something we could spend some time on in the near future. It's certainly something I'd like to see as well!
