### ISSUE TITLE
Marquee component

### ISSUE THREAD

**Issue by VIKTORVAV99** [skeletonlabs/skeleton#1122]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

A marquee component for infinity scrolling animations.

I have a working component bellow I think people would like but I'm not familiar with this repository or how you do things here so opening this issue for feedback before creating any type of PR.

Working code example:
```svelte
<script lang="ts">
	export let duration = 150;
	export let direction: 'normal' | 'reverse' = 'normal';
	export let hover: 'paused' | 'running' = 'running';
</script>

<!--
	@component
	Marquee component.
-->

<div
	class="flex w-full flex-row overflow-x-hidden {$$props.class}"
	style="--marquee-duration: {duration}s;--marquee-direction:{direction};--marquee-hover:{hover}"
>
	<div class="animate-marquee flex-none min-w-full flex-row items-center">
		<slot />
	</div>
	<div class="animate-marquee flex-none min-w-full flex-row items-center">
		<slot />
	</div>
</div>

<style lang="postcss">
	@keyframes marquee {
		0% {
			transform: translateX(0);
		}
		100% {
			transform: translateX(-100%);
		}
	}
	div > div {
		animation: marquee var(--marquee-duration) linear 0s infinite var(--marquee-direction);
	}
	div:hover > div {
		animation-play-state: var(--marquee-hover);
	}
</style>
```
There are some drawbacks to the above component thought.

1. This is done for my own custom use ate the moment so things like color and size of the component will need to either be passed down or set to appropriate defaults (I do think flex-row would work good as a default).
2. This only works for horizontal content right now.
3. Any content need to be wider in than the than the component itself otherwise things start behaving weird.

### What type of pull request would this be?

New Feature

### Any links to similar examples or other references we should review?

I have a working and deployed version of the code on my personal website I'm building with SvelteKit, Tailwind and Skeleton here: https://viktor.andersson.tech/ (It's the animated banner on top.)

**Comment by Cucumberrbob** [comment]
In one of my projects I implemented a shake animation by adding it to the `tailwind.config.js`
I made a quick [stackblitz implementation similar to your website](https://stackblitz.com/edit/skeletonlabs-repl-sdzxta?file=src/routes/+page.svelte) from the starter.
The hover thing is a little odd; Tailwind doesn't provide a class to set the `animation-play-state`, but we can use Tailwind's universal arbitrary variants to select it like `hover:[animation-play-state:paused]`

**Comment by VIKTORVAV99** [comment]
> In one of my projects I implemented a shake animation by adding it to the `tailwind.config.js` I made a quick [stackblitz implementation similar to your website](https://stackblitz.com/edit/skeletonlabs-repl-sdzxta?file=src/routes/+page.svelte) from the starter. The hover thing is a little odd; Tailwind doesn't provide a class to set the `animation-play-state`, but we can use Tailwind's universal arbitrary variants to select it like `hover:[animation-play-state:paused]`
> 
> <img alt="Screenshot 2023-03-20 at 21 53 01" width="469" src="https://user-images.githubusercontent.com/128094686/226475385-7d1d6099-d823-4191-91ee-6974b3a621f8.png">

I did originally add it as a part of the tailwind config but sice it required the content to be wrapped and rendered twice (to avoid clipping and lag) I moved all the code to the component to keep it all in one place. I'm not sure if this is something that makese sense for Skeleton though as we have the all.css file here.

**Comment by endigo9740** [comment]
There's a great article here detailing the `<marquee>` element in HTML:
https://kasp9023.medium.com/what-happened-to-the-marquee-html-element-6ec6782f42ce

If you're not aware, this has been around since the early days of the Internet, but has long since been marked deprecated. However, it still functionally works in all browsers to my knowledge. That said, there are good reasons for why it was deprecated, some technical (never part of the HTML spec; not standardized) as well as the UX concern that, well, they're just kind of annoying. Hidden or non-interactive information is typically considered a bad foundation for UX.

While I think there's edge cases for marques, such as a new ticker, this would be a super niche feature. Skeleton's goal is to focus primarily on primitive elements that can be used like building blocks to builder larger features, pages, and applications. Therefore I cannot justify the time and maintenance cost associated with this one.

For now we will not be moving forward with this request, but thanks for the suggestion!
