### ISSUE TITLE
Pass position to Toast component in ToastSettings

### ISSUE THREAD

**Issue by JustMrMendez** [skeletonlabs/skeleton#1166]
Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

if toast is meant to use as a singleton component, then there should be an option to pass the position through the Toast settings.

```ts
	let toast: ToastSettings = {
		message: 'Transaction submitted successfully!',
		background: 'variant-filled-success',
		classes: 'mt-4',
		position: 't',
		timeout: 5000
	};
```

- t = top, b = bottom, l = left, r = right or  combinations
this is currently possible with the `<Toast position='t' />`

**Comment by endigo9740** [comment]
I feel this falls in the category of "can" rather than "should", if that makes sense.

Technically these are capable of doing this, but the UX for this might be problematic. Generally speaking notifications be uniform to set expectations for users. If I never know which edge or corner it's going to come from I might not understand what it is, and this could cause some level of frustration.

I know for Material Design the toasts are usually anchor to the bottom right corner, then on mobile are bottom centered. But this could be accomplished through some sort of logic that runs and sets this on the parent Toast component.

**Comment by endigo9740** [comment]
@JustMrMendez I opened this up to discussion on the `#contributors` channel on Discord yesterday. The few folks that responded seem to be in agreement with me. While it's technically possible to do this, we don't feel it's good UX practice.

So thank you for the request, but unfortunately this is one we'll be passing on!
