### ISSUE TITLE
Allow setting referrerpolicy on Avatar image

### ISSUE THREAD

**Issue by JoeTodes** [skeletonlabs/skeleton#1185]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

In order to access the user image from a Google account the referrerpolicy of "no-referrer" needs to be set on the <img> tag.

Can we get a prop on the Avatar component to specify the referrerpolicy?

### What type of pull request would this be?

None

**Comment by endigo9740** [comment]
@JoeTodes that seems like something we could add. Thanks for bringing this up.

To contributors: I might actually suggest we go a step further and implement `$restProps` to provide an overflow of any additional props a users might want. In order to do this make sure you follow the suggestions at the bottom of the Conventions section here:
https://www.skeleton.dev/docs/contributing/style-guide#conventions

**Comment by Ddupasquier** [comment]
So I have a question: I've used restProps a lot, but I've only ever used it to provide additional props to the parent-most element of the component. If I have added restProps to the image tag, is this going to receive the provided props from the rendering view properly?

Also, I'm pretty noobish so forgive me for asking, but how do I set up a testing space so I can make sure that these changes are working? :p

**Comment by endigo9740** [comment]
@Ddupasquier a bit off topic here, but you control where restProps are applied. So it could be added anywhere within the component template. Here's the docs, though admittedly it's pretty light:
https://svelte.dev/docs#template-syntax-attributes-and-props

They're most commonly used for Inputs, which tend to have a ton of different configurable attributes available to them.

**Comment by Ddupasquier** [comment]
Ahhhhh, so whatever element has the rest props attribute takes on the propes passed to the component?
Well then if all we want is to add rest props so someone can pass a noreferrer then I can submit this in the morning.

**Comment by endigo9740** [comment]
@Ddupasquier make sure to read the doc I linked above. For Skeleton components we can't use `restProps` verbatim, but have to prune the `class` attribute out of it, otherwise it'll conflict with how we use `class` via `$$props.class` on the parent element.

See an example of `prunedRestProps()` here to see how we go about this:
https://github.com/skeletonlabs/skeleton/blob/dev/src/lib/components/SlideToggle/SlideToggle.svelte#L74

But as long as you follow that we would welcome a PR!

**Comment by Ddupasquier** [comment]
Oh interesting! I'll be reading into this in the morning!
Ideally you will have a PR by the end of the day :)

**Comment by Ddupasquier** [comment]
Is there any opposition to me abstracting this prunedRestProps function into a utils file in the lib/components?
Seems silly to write it in 8 separate components, at this point.

I was commenting in a section as "// Utility Functions" and was like, "... Wait... There's a better way to do this" xD

**Comment by endigo9740** [comment]
Hey I get it, as devs we're beat over the head into writing DRY code. But for Skeleton we actually try to component logic self contained or co-located. Given it's just a couple lines of code I think we're ok to keep these these as is. But thanks for asking!

**Comment by Ddupasquier** [comment]
Awesome! I had a feeling that this was an approach that was being taken, which is why I was sure to ask before going ahead and doing it :p
I've built out a bit of my own component library and more or less try to stick to the same approach. But being so fresh I'm never sure if that is considered a 'best practice' OR just a personal choice in my own implementation xD
