### ISSUE TITLE
Theme selection blocks dropdowns

### ISSUE THREAD

**Issue by jmonroe44** [skeletonlabs/skeleton#1222]
### Link to the Page

https://www.skeleton.dev/docs/themes

### Describe the Issue

The theme & explore dropdowns are positioned behind the theme selector on the Themes portion of the Documentation.

![image](https://user-images.githubusercontent.com/65633244/228414985-6a3fff61-9f1f-4cd8-a03f-ffedbeb71722.png)
![image](https://user-images.githubusercontent.com/65633244/228415370-6704ed01-99e7-4d60-94cb-00f02c6b5147.png)

### Are you able to create a Pull Request with the fix?

No

**Comment by endigo9740** [comment]
Thanks for reporting. Unfortunately this is a weird browser rendering bug between Floating UI popups and elements using backdrop blur. We noted it in the Popup documentation. I'm not aware of a fix, as z-index isn't taken into account at all here.

That said there may be a better way to present the sticky selection UI that side steps this issue.

**Comment by endigo9740** [comment]
@jmonroe44 strangely enough this issue WAS due to z-index, given the selection card is using `sticky`. I've implemented a fix that works for Chrome - see the attached PR to preview.

Also, unrelated, but I wanted to point out that in your screenshots above you appear to have the theme generator previewed turned on in it's default state. This is preventing the background gradient from appearing on the documentation site. Go to the Theme Generator > toggle off/on > then that should resolve your issue.

Thanks!
