### ISSUE TITLE
Popup closequery isn't working

### ISSUE THREAD

**Issue by DevOfManyThings** [skeletonlabs/skeleton#1229]
### Current Behavior

Popup closequery isn't working, the popup remains open even when the correct element is interacted with.

### Steps To Reproduce

On the current production docs you can see the issue when interacting with the combobox example: https://www.skeleton.dev/utilities/popups

Gif example: 
![2023-03-29_19-19-56](https://user-images.githubusercontent.com/6001393/228636681-f20b1749-3d23-4f78-9bf3-2a54d7f6d29e.gif)

### Anything else?
Tagging both of you as requested on discord: @endigo9740 @Cucumberrbob 
_No response_

**Comment by endigo9740** [comment]
@Cucumberrbob just including you here as well in case you can get to this before I do.

**Comment by Cucumberrbob** [comment]
Problem here is that I didn't reimplement the closing in the `onWindowClick` handler 🤦 . 
I'm happy to write a PR to fix this, I have a working solution by adding a `onPopupClick` handler, which only runs the `closeQuery` bits of `onWindowClick`.

The focus after clicking an option is a little weird though - focus will return to the popup's trigger after pressing tab unless you click the last option in the combobox. This is because the focus is moved back to the trigger when an element inside the popup is focussed and the popup is shut. I haven't found a clean solution to moving the focus out of the popup yet. 

In the video below, I click the first option, press tab (which focusses the trigger), then click the final option, and press tab again (which focusses the next element after the popup).


https://user-images.githubusercontent.com/128094686/228824117-7b878a98-bdca-4579-9b62-4598d1f0129b.mp4

**Comment by endigo9740** [comment]
@Cucumberrbob Yeah I think having the closeQuery feature takes priority over to the focus weirdness here, but I can maybe take a look once a PR is ready.
