### ISSUE TITLE
can't disable any child elements from closing the popup

### ISSUE THREAD

**Issue by jer-0** [skeletonlabs/skeleton#1318]
### Current Behavior

Hello, the docs says setting `closeQuery: ''` means "no chidren will close the popup" 

according to this line: 
https://github.com/skeletonlabs/skeleton/blob/2a6b76655a1e6c5eb33ce796bb781b5108b19c85/src/lib/utilities/Popup/popup.ts#L97

setting `closeQuery: ''` ->  `(args.closeQuery || 'a[href], button')` -> `('' || 'a[href], button') = 'a[href], button'`

so `closeQuery: ''` = `closeQuery: 'a[href], button'` 

what if you want to disable any child elements from closing the popup?.

**Comment by endigo9740** [comment]
@jer-0 yep there's a flaw in the logic here since `''` will be treated as a false state. Until resolved you could use a fake query to prevent any element from closing the popup, something like `x` since `<x>` isn't a real element.

> what if you want to disable any child elements from closing the popup?

Sounds like you're asking about the opposite, anything closing it. In this case you would use the wildcard `*` just like the CSS selector.
