### ISSUE TITLE
Stepper `buttonNextType` doesn't seem to work

### ISSUE THREAD

**Issue by cmintey** [skeletonlabs/skeleton#1328]
### Current Behavior

I am trying to have a different form on each step of a stepper. After the user clicks "next", the form should be submitted but it doesn't. It does work on "complete" though.

### Steps To Reproduce

1. Create a Stepper with two steps
2. Wrap each step in a `form` tag
3. Observe that step 1 does not submit when clicking "next" and step 2 *does* submit on "complete"
4. Notice that in step 1, if a button with type "submit" is present and clicked, the form does get submitted.

Here is minimal reproducible code:

```svelte
<Stepper buttonNextType="submit" buttonCompleteType="submit">
	<form
		method="POST"
		use:enhance={() => {
			console.log("submit");
		}}
	>
		<Step buttonNextType="submit">
			<svelte:fragment slot="header">Name</svelte:fragment>

			<label for="name">
				<span>Name</span>
				<input class="input" type="text" id="name" name="name" autocomplete="name" required />
			</label>
			<button class="btn variant-filled" type="submit">Submit</button>
		</Step>
	</form>

	<form
		method="POST"
		use:enhance={() => {
			console.log("submit");
		}}
	>
		<Step buttonNextType="submit">
			<svelte:fragment slot="header">Group</svelte:fragment>

			<label for="group">
				<span>Group</span>
				<input class="input" type="text" id="group" name="group" autocomplete="off" required />
			</label>
			<button class="btn variant-filled" type="submit">Submit</button>
		</Step>
	</form>
</Stepper>
```

### Anything else?

I have also tried including the `form` within the Step itself

**Comment by endigo9740** [comment]
@cmintey this one has me a bit puzzled. I have definitely replicated the issue with your snippet (thanks for providing that). What odd is if I inspect the Next button, it's clearly indicated to be of type Submit:

![Screenshot 2023-04-14 at 4 55 24 PM](https://user-images.githubusercontent.com/1509726/232161587-b79a8c1c-c012-45ec-89ea-7252e68ae0f3.png)

But the form submission does not occur. However if I tap the slot-provided submit button it does.

I know for a fact that the Stepper buttons are capable of triggering form submits, because we had users report this happening mistakenly early on because our buttons did not have a specific `type` attribute defined. When this occurs they default to `type="submit"`.

I also tested hardcoding your submit button within the component itself, in the same location the default slot resides. When I do this submission works as expected.

![Screenshot 2023-04-14 at 4 58 30 PM](https://user-images.githubusercontent.com/1509726/232161914-5dd91c76-8288-4720-9d7b-2acfd47df46e.png)

I thought perhaps there may be an issue with Svelte/Forms not liking a dynamically set `type` attribute on the button. However, hardcoding the Next button to use type `submit` is not working either:

![Screenshot 2023-04-14 at 5 01 17 PM](https://user-images.githubusercontent.com/1509726/232162204-79c2cd8b-b393-492f-bc20-617458b27a7c.png)

So there's something else at play here. There's a number of dynamic values for the button, including the type, classes, label, disabled attribute, and of course the click handler. I think it's some combination of these at place that's breaking things.

What I'm going to need to do is strip this down to a minimal reproduction in the Svelte REPL and reach out to either our community or Svelte support to see if anyone can help diagnose this. Unfortunately I will have to circle back to this, so I apologize for the delay! I'm also going to mark this "help wanted" in case others see it and troubleshoot.

Sorry for the issue in the meantime!

**Comment by endigo9740** [comment]
@cmintey I just wanted to call attention to @AdrianGonz97's PR which appears to resolve this. I'll test this next week and plan to merge if then. Hopefully this helps!

https://github.com/skeletonlabs/skeleton/pull/1333

**Comment by cmintey** [comment]
This is great! Thank you both for the quick work on this! @endigo9740 @AdrianGonz97
