### ISSUE TITLE
Unused .dark CSS Selector

### ISSUE THREAD

**Issue by JP-Ellis** [skeletonlabs/skeleton#1335]
### Current Behavior

When using the various `[...]-[color]-[num]-[num]-token` directives, I get a warning of an unused `.dark .foo` selector and the corresponding element on the page does not respond to changes when the LightSwitch component is toggled. It would appear that since the `.dark .foo` directive is deemed as unused, it is removed from the generated output.

### Reproduction / Steps To Reproduce

An example of StackBlitz can be found [here](https://stackblitz.com/edit/skeletonlabs-repl-zynyau?file=src/routes/+page.svelte). The only files changed to reproduce this example were the `+page.svelte` and `+layout.svelte` with no other configuration affected.

**Comment by Sarenor** [comment]
https://stackblitz.com/edit/skeletonlabs-repl-z67feq?file=src/app.postcss

I didn't change much to make it work:
Just moved your class declarations from a Svelte-File into ``app.postcss``.

I'm not sure if I ever saw classes generated with Tailwind ``@apply`` inside a Svelte Component working.
We'd have to investigate the final build, since it might conflict with some of the preprocessing Svelte itself does.

**Comment by JP-Ellis** [comment]
While I can see what what you did does resolve the issue, this does not seem like a very practical way of doing things. One appeal of using Svelte is that components can be defined with their associated TypeScript and PostCSS together in the one file/folder (especially nice for particularly small components). Having to split the PostCSS and storing it all into a global file feels somewhat wrong.

I will admit that I am no expert with web development and Svelte, but is this really the only way forward?

Is it possible to configure PostCSS to recognise all `.dark`-prefixed selectors as being in use even if they don't appear within the file itself?

**Comment by endigo9740** [comment]
@JP-Ellis while what you're saying is true, Svelte components house your script, template, and styles within a single components. That's not really the best way to utilize Tailwind, regardless of framework. For Tailwind the best practice is to lean into the utility-first approach, which means using your classes in the template, rather than in a `<style>` tag.

https://tailwindcss.com/docs/utility-first

Through the whole of Skeleton we only have a few instances where we use `<style>` tags in fact. It can feel odd and foreign at first (trust me, I've done traditional CSS for 20+ years), but there are bundle benefits to using this inline approach - given the same primitive classes are used over and over. Just like there's detriments to the `@apply` method, which can increase your bundle size. Tailwind mentions this in the linked.

When you're talking dark variant specific you implement these with the preview `dark:`:
https://tailwindcss.com/docs/dark-mode

**Comment by JP-Ellis** [comment]
Thanks for the explanation, much appreciated! I will be refactoring my components to make use of Tailwind's utility-first approach 😄

I'll keep this ticket open, leaving it up to you to decide what to do with it.
