### ISSUE TITLE
Differentiate popup navigation list focus and selection styles

### ISSUE THREAD

**Issue by jeromecc** [skeletonlabs/skeleton#1345]
### Current Behavior

Hello!

I'm trying to highlight the nav list item which corresponds to the current page in my AppBar navigation lists.

I'm using the same code as sketelon.dev, which works well for highlighting the current page on SideBar and Drawer.

For AppBar nav lists, I'm using something similar, as suggested in the docs: "To highlight active state, we recommend conditionally applying a background color to the anchor tag" (the documentation should be updated to use "bg-primary-active-token" instead of "!bg-primary-500" . It gives better results in dark mode.

```
$: classesActive = (href: string) => {
		return $page.url.pathname === href ? 'bg-primary-active-token' : '';
	}
```

The current page is highlighted. The bug is that the first item of each navlist always remains highlighted. The same thing happens in skeleton.dev (first item of "Explore" menu is always highlighted: "Home").

Interestingly, this does not happen on the Theme menu, where only the current theme is highlighted.

If I remove ```class="list-nav"``` from the nav element, highlighting works correctly but styling is lost. :(

Thank you! :)

**Comment by Sarenor** [comment]
Can't really investigate but I've got a working nav list on https://arsnouveau.wiki.dev
https://github.com/Sarenor/arsnouveau-wiki/blob/dev/src/lib/components/navigation/Navigation.svelte

**Comment by jeromecc** [comment]
Hi @Sarenor! Thanks for the reply. I checked your repo. You are using the nav list in the sideBar left slot. It also works fine for me there. The problem I described  is in the AppBar at the top of the page. Just like on skeleton.dev my users can access the same pages through the AppBar and through the sideBar.
[Off topic:  I had a look at  https://www.arsnouveau.wiki and I noticed a bug (on Firefox 111.0.1): I selected an addon at the top in the AddOn selection menu. It worked. But then I tried to select another one and it didn't work. The popup is stuck.]

I'm pretty sure it's a skeleton bug cause it is apparent on skeleton.dev website and disappears if I remove the skeleton specific styling class...

**Comment by endigo9740** [comment]
The "AppBar nav lists" is just a list inserted into a popup. It has nothing specific to do with lists or the app bar. So let's make sure we're using the correct semantics here - what is being described is the Popup utility behavior.

When using the popup you have a number of different event types available to you. On our documentation site, we use the `click` event type. By default, the logic for this highlights the first focusable element when the popup is opened. This is intentional to meet ARIA APG guidelines for a11y:

https://www.w3.org/WAI/ARIA/apg/patterns/menubar/

> When a menu opens, or when a menubar receives focus, keyboard focus is placed on the first item.

However, you and others have expressed some concern that the focus styling looks the same as the selected styling for lists. Which can sometimes cause some confusion. So the fix here is to make the focus style different than the selected style so it's more obvious what is occurring. But the functionality is expected and desired.

If you do not wish to focus the first item, but rather keep focus on the trigger. That's where the `focus` and `focus-click` events come into play. They're typically used for inputs (ex: autocomplete popups) but may provide the behavior you seek.

**Comment by jeromecc** [comment]
Thank you very much for the thorough explanation @endigo9740 ! I noticed that the apprail and drawer are not accessible through the keyboard and do not seem to follow these ARIA rules.

My poor design and web skills do not allow me to imagine the perfect solution to visually differentiate selected/active, focus, hover and "normal" links, particularly button links. My target audience is very wide and I'm trying to make everything as easy and obvious as possible.

Do you think it would be wrong or unwise to use the hover style for focus?

**Comment by endigo9740** [comment]
> I noticed that the apprail and drawer are not accessible through the keyboard and do not seem to follow these ARIA rules.

Just so we're clear, the App Bar is the header bar at the top of the page. The App Rail is the vertical bar with navigation icons alongside the left side of the inner pages of our doc site:

- https://www.skeleton.dev/components/app-bar
- https://www.skeleton.dev/components/app-rail

Nothing in the prior discussion above was discussion the rail or drawer, so I'm not sure the relevance here. Both the bar are keyboard accessible (using tab / shift+tab) as expected. And the only relevant for the drawer is ensuring focus remains within the drawer while it's open. Drawers are like modals and automatically utilize our focus trap action for this. So again, I'm not sure where you're going with this.

> My poor design and web skills do not allow me to imagine the perfect solution to visually differentiate selected/active, focus, hover and "normal" links, particularly button links. My target audience is very wide and I'm trying to make everything as easy and obvious as possible.

Sorry, I should have been more clear. I listed that as the actionable change for this ticket. It's the change me (or another contributor) will implement to resolve and close out this ticket. You can monitor this issue to track progress as this occurs in the near future. I'm not sure offhand what style will be used exactly, but we'll test while implementing the change.

**Comment by endigo9740** [comment]
FYI, I know this will be a list style update, but we these need the new focus styles to work in conjunction with popups, so I'm going this change under some pending refactors and extensions to the popup detailed here:
https://github.com/skeletonlabs/skeleton/issues/1350

**Comment by ecejeff** [comment]
I am just getting started using Skeleton, and I have encountered this issue. It looks like there's a fix planned, which is great.

Anyone know a quick fix to change the focus style to be more like hover? Something quick and dirty is great, because I'll just be removing it when the real bug fix is implemented.
