### ISSUE TITLE
Drawer padding property confusing/conflicting name

### ISSUE THREAD

**Issue by Hugos68** [skeletonlabs/skeleton#1383]
### Current Behavior

The padding property in any DrawerSettings object will affect the backdrop and not the drawer itself.

### Reproduction / Steps To Reproduce

1. Create a DrawerSettings object
2. Set padding to any value (as long as its visible to the naked eye (2, 4, 8 etc)
3. Watch is being applied to backdrop.

### Anything else?

I'd highly recommend to change padding to paddingBackdrop to be in line with the names of other backdrop properties and possibly even add the padding property for the drawer itself aswell.

**Comment by endigo9740** [comment]
We have a naming style convention where we try to avoid using two word camel-case prop names when we can avoid it. I think for now we just need to adjust the JSDoc comment to indicate this is a Backdrop prop instead of a Drawer prop. Likewise renaming the prop would be a breaking change.

https://github.com/skeletonlabs/skeleton/blob/dev/src/lib/utilities/Drawer/Drawer.svelte#L32
