### ISSUE TITLE
Add Checkbox Variants: secondary, tertiary

### ISSUE THREAD

**Issue by marchellodev** [skeletonlabs/skeleton#1416]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

It seems like it is impossible to create secondary or tertiary checkboxes. Only `input-success`, `input-warning` and `input-error` modifiers are supported. In addition, specifying custom colors altogether would be really nice.

### What type of pull request would this be?

Enhancement

### Any links to similar examples or other references we should review?

[Daisy UI Example](https://daisyui.com/components/checkbox/)

**Comment by endigo9740** [comment]
Hey @marchellodev, I see your point, but we're trying to keep variant styles agnostic and reusable across a variety of elements. Most that exist now can affect cards, buttons, badges, etc. This would be a bit niche.

> It seems like it is impossible to create secondary or tertiary checkboxes. 

Not at all. I'm guessing you tried applying something like `class="bg-secondary-500"` and it didn't work? If so that's because you have to follow the same selector method we used, which is to styled only the `:checked` state. Here's what that looks like in our source:

```css
.checkbox:checked,
.radio:checked {
    @apply bg-primary-500 hover:bg-primary-500 focus:bg-primary-500 focus:ring-0;
}
```

Tailwind provides support for selectors such as this:
https://tailwindcss.com/docs/hover-focus-and-other-states#checked

```html
<input type="checkbox" class="checked:bg-secondary-500 checked:hover:bg-secondary-500 checked:focus:bg-secondary-500" />
```

That's a bit verbose, so if you want something more compact you could create your own local variants in your `app.postcss` global stylesheet:

```css
.variant-checkbox-secondary:checked {
	@apply bg-secondary-500 hover:bg-secondary-500 focus:bg-secondary-500;
}
```

Hope this helps!

**Comment by marchellodev** [comment]
Thanks!!
