### ISSUE TITLE
Allow alternative labelFieldName and valueFieldName option

### ISSUE THREAD

**Issue by marcsumilang** [skeletonlabs/skeleton#1422]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

![image](https://user-images.githubusercontent.com/47217877/235846811-738be2e9-ebe5-4e89-adae-ca1524e4b9eb.png)

### What type of pull request would this be?

New Feature

### Any links to similar examples or other references we should review?

https://github.com/pstanoev/simple-svelte-autocomplete

**Comment by Sarenor** [comment]
A bit more explanation than a screenshot of another projects github page would be appreciated.

You would kike to have additional props on the AutoComplete that allow you to specify a key under which the value/label for an object is gotten if I understood you correctly?

So if you have ``<Autocomplete labelFieldName="showMe" valueFieldName="submitMe">`` and this data:
```js
{
   value: "test",
   label: "Not my label",
   showMe: "This is the label",
   submitMe: "This is the value"'
}
```
You'd be shown "This is the label" and "This is the value" would be submitted.

Correct?

**Comment by marcsumilang** [comment]
> A bit more explanation than a screenshot of another projects github page would be appreciated.
> 
> You would like to have additional props on the AutoComplete that allow you to specify a key under which the value/label for an object is gotten if I understood you correctly?
> 
> So if you have `<Autocomplete labelFieldName="showMe" valueFieldName="submitMe">` and this data:
> 
> ```js
> {
>    value: "test",
>    label: "Not my label",
>    showMe: "This is the label",
>    submitMe: "This is the value"'
> }
> ```
> 
> You'd be shown "This is the label" and "This is the value" would be submitted.
> 
> Correct?

Yes, that is correct. Thank you for clarifying! 

To reiterate, the additional props on the AutoComplete component would allow for specifying the key under which the label and value are obtained for each object in the data array. 

This `<Autocomplete labelFieldName="showMe" valueFieldName="submitMe">` would provide more flexibility and customization options for the AutoComplete component.

**Comment by marcsumilang** [comment]
Yes, that is correct. Thank you for clarifying! 

To reiterate, the additional props on the AutoComplete component would allow for specifying the key under which the label and value are obtained for each object in the data array. 

This `<Autocomplete labelFieldName="showMe" valueFieldName="submitMe">` would provide more flexibility and customization options for the AutoComplete component.

**Comment by endigo9740** [comment]
No response, so I'm going to close this out. If the example above does not satisfy your need please let me know and we can look to reopen this. Thanks.

**Comment by Sarenor** [comment]
Sorry, haven't checked my email in a long while, basically the thought was that you have a very big list of AutoComplete Items coming from an API for example in the following format:
```js
[
  {
    thisIsTheValue: 'value',
    thisIsTheLabel: 'label'
  },
  [...]
]
```
And instead of having to do an expensive map for each entry you can tell the Autocomplete to look into the ``thisIsTheValue`` prop for the value and into ``thisIsTheLabel`` for the label.

Kinda like this:

```html
<Autocomplete labelFieldName="thisIsTheLabel" valueFieldName="thisIsTheValue">
```
Similar to how you give the object accessor property to the Table component

**Comment by endigo9740** [comment]
That would be lead to the component mapping instead of the user mapping or finding the data, which I think would be ill-advised though. If the concern is local mapping in the client is going to be slower, this isn't going to solve that issue. This is where the server or API providing the data really needs to be in charge of updating the structure. There's not really going to be a quicker or more optimal solution than that.

**Comment by Sarenor** [comment]
The component wouldn't really have to map the data though, only access it, no?

But I generally agree that it's not an immediately necessary optimization
