### ISSUE TITLE
Accordions in Drawers (or in general?) have wonky Tab shortcuts

### ISSUE THREAD

**Issue by MrVauxs** [skeletonlabs/skeleton#1423]
### Current Behavior

When inside of a Drawer, attempting to navigate down an AccordionsItems ends up becoming impossible **unless** they were open already. However, when you close the Accordion in this scenario (with the accordion already open prior to tabbing through it), you are able to tab outside of the drawer.

https://user-images.githubusercontent.com/32039708/236020851-c7b51531-f146-4217-b3fd-c817e8eef1c8.mp4

### Reproduction / Steps To Reproduce

https://stackblitz.com/edit/skeletonlabs-repl-kh4qc3?file=src/routes/+layout.svelte

### Anything else?

Discord Thread: https://discord.com/channels/1003691521280856084/1103386196350095400/1103386196350095400

**Comment by MrVauxs** [comment]
Even more bizarre! This bug only affects the last AccordionItem!

**Comment by endigo9740** [comment]
@MrVauxs so I've dug into this a bit further and finally realize what's happening. You've stumbled upon a one heck of a bug here.

For context, here's a summary of how an AccordionItem template is rendered. It includes the trigger button that toggles the panel below. The panel contains the contents for that item.

![Screenshot 2023-05-04 at 4 36 30 PM](https://user-images.githubusercontent.com/1509726/236335456-21ebdd6c-4ea8-487e-b3c8-78e5811889c2.png)

What's happening here is when the AccordionItem is placed within a modal or drawer, it's subject to the rules of the Focus Trap action we implement on these modals-like features by default:
https://www.skeleton.dev/actions/focus-trap

The focus trap has two goals:

1. Find the first focusable element within the target region. When shift+tab is pressed, jump to the last focusable item
2. Find the last focusable element within the target region. When tab is pressed, jump to the first focusable item

This means the tab pathing is circular and you can't escape the modal element (the drawer in this case). This is a very important accessibility feature that prevents folks screen readers from accidentally escaping the overlay elements.

However, this is causing an issue with accordions specifically, which I'll try to visualize below:

```
AccordionItem (open)
    button
    panel (visible)
AccordionItem (closed)
    button
    panel (hidden)
AccordionItem (closed)
    button
    panel (hidden)
```

For most Accordions either no Item or the first item will be the only ones open when the Drawer opens. This means the panel for the second and last items are hidden. The problem arises is when the drawer opens, the Focus Trap actions runs, but it MISSES the final panels children elements because they are hidden in the DOM. So as far as the action is concerned the "last focusable element" is the Button for the third AccordionItem!

I'm not 100% sure how I'm going to solve this quite yet. My knee jerk relation would be to change the AccordionItem from using a Svelte `#if` template condition to render/hide the panel in the visible state and instead just collapse the height. Meaning this contents of this element are always visible to the DOM - and thus the Focus Trap action.

That said, I'm going to open this up to discussion on Discord to see if anyone else has any better ideas. But hope this helps you understand what's going on! It's a doozy!

**Comment by MrVauxs** [comment]
Every framework, every software, every project I go to, my title of Bugfinder comes back to haunt me.

**Comment by endigo9740** [comment]
Ha, well sometimes breaking stuff can bring attention to bugs like this.
