### ISSUE TITLE
Broken Link in Preview of Docs in Dev Branch for Chat Block

### ISSUE THREAD

**Issue by riziles** [skeletonlabs/skeleton#1438]
### Link to the Page

https://skeleton-docs-git-feat-chat-prompt-skeleton-labs.vercel.app/elements/chat

### Describe the Issue

@endigo9740 , 

In the "On This Page" nav list off to the right in the dev preview of the new docs for the "Chat" block, the anchor link for the "Prompt" section doesn't work. Apologies, I've been trying for a while to figure out how to fix it and submit a PR, but I'm at a dead end.

![image](https://user-images.githubusercontent.com/98712531/236374664-602c4b19-3c8b-49d6-b910-ae89874bc853.png)

### Are you able to create a Pull Request with the fix?

No

**Comment by adityakode** [comment]
I would love to work  on this !

**Comment by endigo9740** [comment]
@riziles the bug is in the table of contents, which is known to have several issues, and not the Chat page as far as I can tell.

I'm going to mention this issue there, and close this as a duplicate:
https://github.com/skeletonlabs/skeleton/issues/1030

@adityakode I appreciate the offer, but best to leave this one to me. It's not going to be a trivial update. See #1341 if you're looking for a smaller scope issue to jump on though. Thanks!

**Comment by adityakode** [comment]
Sure!
