### ISSUE TITLE
The search for the Skeleton website loses focus trap after searching anything.

### ISSUE THREAD

**Issue by Hugos68** [skeletonlabs/skeleton#1444]
### Current Behavior

After searching anything without going somewhere you are able to tab out of the search modal into the backdrop and tab through the site.

### Reproduction / Steps To Reproduce

1. Go to https://www.skeleton.dev/
2. Hit CMD/CTRL + K
3. Type "tables" for example
4. Hit tab until you tab outside of the modal into the actual site whilst being in the search modal

### Anything else?

It's interesting that if you only type 1 letter, then hit backspace it still allow you to get out so I feel like it has to do with how autocomplete filters

**Comment by Mahmoud-zino** [comment]
I was investigating this issue when I found the problem is that the FocusTrap scans for `focusable Elements` on initialize and never updates the list.

so when opening the search let's say we have about 60 elements in the list and when typing something the FocusTrap thinks it still has 60 elements, which is causing the problem.

Possible solutions:
1. The user has to notify the FocusTrap to scan again when the children list changes. (not sure how or if it is possible)
2. The FocusTrap scans constantly for changes in the children's list. (something like MutationObserver maybe?!)

**Comment by endigo9740** [comment]
Great fine. Yeah we're investigating ways to improve focus trap and it's seemingly the same issue on both tickets. Number 2 sounds more likely as the best approach, as modals and drawers likely won't have a direct means to interface with the focus trap action.

I'll circle back once I've had a chance to look into this a bit deeper.

**Comment by Mahmoud-zino** [comment]
@endigo9740 Is it ok if I tried to implement the solution?
I want to try a couple of different things and if I have something clean I would create a PR.
No promises I just find the bug interesting :)

**Comment by endigo9740** [comment]
You're welcome to take a stab at this, but it's a fairly complex bug. I detailed the overall issues here:
- https://github.com/skeletonlabs/skeleton/issues/1423#issuecomment-1535452016

The ideal fix will address this for BOTH use cases - both for modals and drawers. I'd definitely welcome help with it though, as it's quite a challenging issues!
