### ISSUE TITLE
undefined class in toast DOM element

### ISSUE THREAD

**Issue by ZirionNeft** [skeletonlabs/skeleton#1480]
### Current Behavior

Just noticed it when using dev console
![image](https://github.com/skeletonlabs/skeleton/assets/23456328/7ed27722-882f-4474-87d8-4c7b48f8697b)

### Reproduction / Steps To Reproduce

Click some toast example button in https://www.skeleton.dev/utilities/toasts then check DOM element

**Comment by SebasF1349** [comment]
Looks like this happens when `classes` is not used in the toast settings and so `t.classes` in undefined (https://github.com/skeletonlabs/skeleton/blob/master/src/lib/utilities/Toast/Toast.svelte#L114)

Changing `{t.classes}` to `{t.classes ?? ""}` should fix it (I don't see any default styling as in background).

Should be a pretty easy change and I can do the pr if you agree.

**Comment by ZirionNeft** [comment]
Sure, feel free to PR
