### ISSUE TITLE
Tapping modal backdrops on mobile can trigger close multiple times

### ISSUE THREAD

**Issue by tizu69** [skeletonlabs/skeleton#1544]
### Current Behavior

When on mobile, multiple queued modals close at one (the current and the next one) if just tapping on the backdrop.

### Reproduction / Steps To Reproduce

Use the queued modals Button from the docs on a touchscreen-enabled device 

### Anything else?

[video](https://media.discordapp.net/attachments/1058430318018822286/1110530591805411458/screen-20230523-1158142.mp4)

**Comment by tizu69** [comment]
> the user's finger can remain on the backdrop for long enough that it triggers the close event twice. 

Seems weird to me - it only occurs when you don't hold your finger and just tap.

**Comment by Mahmoud-zino** [comment]
I just looked into this and this is actually happening because we are reacting to `mousedown` and `touchstart` so tapping on Android, for example, would trigger both.
to solve this we only need `event.preventDefault();` in the `onBackdropInteraction`.
I would be happy to fix it if this was the best solution.
