### ISSUE TITLE
Allow user to define their own test-id's for components

### ISSUE THREAD

**Issue by Hugos68** [skeletonlabs/skeleton#1653]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

I am testing my app and currently the testId is already defined for modal, I'd like this to be customizable.
So I'd like the modalSettings type to allow for passing in a test id for playwright, or just allow restprops to be passed through.

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
@Hugos68 we actually implement test ids for all components as part of our standard practice. This is done for Vitest, but Playwright should be able to utilize these as well. The format is as follows:

```html
<div class="accordion-item ..." data-testid="accordion-item">
```

You'll just need to query by the `data-testid`.

Additionally every component has ID-like classes if you need to navigate through the component template. We call them "selector classes", since they're primarily geared towards creating global style selectors:
https://www.skeleton.dev/docs/styling#global-styles-overrides

For custom modals you have full control over the template within the modal. I'd recommend you set your own IDs there.

I could -maybe- see a need to set a unique ID per the standard (alert, confirm, prompt), but given there's only ever one modal displayed at a given time, an ID might be a bit redundant for testing purposes.

**Comment by Hugos68** [comment]
> @Hugos68 we actually implement test ids for all components as part of our standard process. This is done for Vitest, but Playwright should be able to utilize these as well. The format is as follows:
> 
> ```
> <div class="accordion-item ..." data-testid="accordion-item">
> ```
> 
> You'll just need to query by the `data-testid`.
> 
> Additionally every component has ID-like classes if you need to navigate through the component template. We call them "selector classes", since they're primarily geared towards creating global style selectors: https://www.skeleton.dev/docs/styling#global-styles-overrides
> 
> For custom modals you have full control over the template within the modal. I'd recommend you set your own IDs there.
> 
> I could -maybe- see a need to set a unique ID per the standard modals (alert, confirm, prompt), but given there's only ever one modal displayed at a given time, an ID might be a bit redundant for testing purposes. At that point it sounds like you're testing our implementation rather than your app.



> @Hugos68 we actually implement test ids for all components as part of our standard process. This is done for Vitest, but Playwright should be able to utilize these as well. The format is as follows:
> 
> ```
> <div class="accordion-item ..." data-testid="accordion-item">
> ```
> 
> You'll just need to query by the `data-testid`.
> 
> Additionally every component has ID-like classes if you need to navigate through the component template. We call them "selector classes", since they're primarily geared towards creating global style selectors: https://www.skeleton.dev/docs/styling#global-styles-overrides
> 
> For custom modals you have full control over the template within the modal. I'd recommend you set your own IDs there.
> 
> I could -maybe- see a need to set a unique ID per the standard modals (alert, confirm, prompt), but given there's only ever one modal displayed at a given time, an ID might be a bit redundant for testing purposes. At that point it sounds like you're testing our implementation rather than your app.

That makess sense for my use case yeah but does that cover all testing software, and maybe these testing id's can be exposed on the documentation? Because I had to dig through the source code to find them. Testing is become more and more doable for frontend apps so maybe something to consider in the future.

**Comment by endigo9740** [comment]
Sorry for the incredibly late reply on this issue Hugos, but between the Store launch and v2 my time has been very limited lately!

> and maybe these testing id's can be exposed on the documentation
Unless Sveld updates to support something like this, we don't have a way to automate this. Which means it would have to be done manually. We go out of our way to avoid manual documentation, because while it's simple for one component. Keeping this data accurate for an entire library becomes a BIG lift. So this is not likely to happen. The source will remain the best source for this info. But we do provide the "source" button on each doc page for quick access.

> Testing is becoming more and more appropriate for frontend apps so maybe something to consider in the future.
User should never be testing third party libraries. It's our responsibility to test our components and features to ensure they work. I understand you're talking about testing in a more e2e manner in your own app, using our features, but want to make sure the where that line should be drawn.

That said, we do provide ids on the top level of each wrapping parent in component. Access the children of any target element should be trivial for any testing suite (ex: `.avatar img`). I'm not sure we can really do any more to improve this situation beyond what's provided now.

If you (or anyone else) is interested in improving the testing story in Skeleton though, the literal single oldest ticket in our backlog is related to this. Unfortunately neither myself or any volunteers have made headway on it. But I do think it's something important that should be revisited in the near future:
https://github.com/skeletonlabs/skeleton/issues/150
