### ISSUE TITLE
Vertical Radio button group

### ISSUE THREAD

**Issue by TSRChapman** [skeletonlabs/skeleton#1672]
### Current Behavior

verticle radio group is slightly out of alignment from the top radio to the second radio

### Expected Behavior

verticle alignment on all radio buttons

### Steps To Reproduce

visible on the documentation page for radio button groups showing the vertical arrangement

### Link to Reproduction / Stackblitz

https://www.skeleton.dev/components/radio-groups

**Comment by endigo9740** [comment]
Appending a quick screenshot to show the error - note the second item is a bit off when the hover state is triggered:

![Screenshot 2023-06-19 at 12 02 40 PM](https://github.com/skeletonlabs/skeleton/assets/1509726/1846d55b-9853-4745-ba0b-9869df1f2961)

The issue seems to be the spacing. Even in the vertical orientation it's still using `space-x`
