### ISSUE TITLE
Resolve issue with button groups and child variant precedence

### ISSUE THREAD

**Issue by knarkzel** [skeletonlabs/skeleton#1725]
### Current Behavior

Currently it's only possible to have one style for all the buttons in `btn-group`.

### Expected Behavior

Be able to use different styles for each button in `btn-group`.

### Steps To Reproduce

```html
<div class="btn-group">
  <button class="variant-filled-primary">Monthly</button>
  <button class="variant-ghost-primary">Annually</button>
</div>
```

![image](https://github.com/skeletonlabs/skeleton/assets/85593302/803d10b1-2075-4eee-ba16-661542c8d048)

### Link to Reproduction / Stackblitz

https://discord.com/channels/1003691521280856084/1125913854585618534

### More Information

As you can see in the screenshot above, the colors are off. `--on-primary` doesn't work properly, borders aren't grouped etc.

**Comment by endigo9740** [comment]
Appending a bit of additional context here:

We likely won't support mixing and matching button variants in a group. If the buttons are moving towards a uniform style they should likely not be grouped.

But we are seeing an issue with `variant-filled-x` not applying the text/fill "on" color when doing something like this:

```html
<div class="btn-group variant-ghost-primary">
  <button class="variant-filled-primary">Monthly</button>
  <button>Annually</button>
</div>
```

Which could be useful for creating a radio group like grouping that indicates active selection state. It seems the `btn-group > button` styles are taking precedent for text color, which means the text will flip flop between black/white when toggling themes instead of adhering to the desired "on" color, which harms accessibility.

There's like something sort of `!` important declaration on the button group styles that is causing this.

**Comment by endigo9740** [comment]
Just reiterating that the original post above was not an scenario we were keen to support in Skeleton. If you wish to mix and match variants, create your own button grouping.

However, per having a variant override to indicate state (like a radio field), this appears to be resolve in Skeleton v2. You're now able to supply `!` on the variant class to signal that it should take precedence, so like:

```html
<div class="btn-group variant-ghost-primary">
	<button class="!variant-filled-primary">Months</button>
	<button>Days</button>
	<button>Years</button>
</div>
```

Not only does the text color then work as expected, but the child button with the variant also stays active even when hovering the button. It's a small change that makes this work exactly as expected.

With this, no changes are needed on Skeleton's end.
