### ISSUE TITLE
Popup has delay when closing

### ISSUE THREAD

**Issue by jin2255** [skeletonlabs/skeleton#1748]
### Current Behavior

when closing popup by clicking outside or button, it has a bit delay

### Expected Behavior

but I think  it must be closed immediately

it is close function of utilities
```    
function close(callback) {
        if (!elemPopup)
            return;
        // Set transition duration
        const cssTransitionDuration = parseFloat(window.getComputedStyle(elemPopup).transitionDuration.replace('s', '')) * 1000;
        setTimeout(() => {
            // Set open state to off
            popupState.open = false;
            // Return the current state
            if (args.state)
                args.state({ state: popupState.open });
            // Update the DOM
            elemPopup.style.opacity = '0';
            elemPopup.style.pointerEvents = 'none';
            // Cleanup Floating UI autoUpdate (close only)
            if (popupState.autoUpdateCleanup)
                popupState.autoUpdateCleanup();
            // Trigger callback
            if (callback)
                callback();
        }, cssTransitionDuration);
    }
```

but in my opinion, it must be shown like this?
```    
function close(callback) {
        if (!elemPopup)
            return;
        // Set transition duration
        const cssTransitionDuration = parseFloat(window.getComputedStyle(elemPopup).transitionDuration.replace('s', '')) * 1000;
        // Set open state to off
        popupState.open = false;
        // Return the current state
        if (args.state)
            args.state({ state: popupState.open });
        // Update the DOM
        elemPopup.style.opacity = '0';
        elemPopup.style.pointerEvents = 'none';        
         setTimeout(() => {
            // Cleanup Floating UI autoUpdate (close only)
            if (popupState.autoUpdateCleanup)
                popupState.autoUpdateCleanup();
            // Trigger callback
            if (callback)
                callback();
        }, cssTransitionDuration);
    }
```

it's just my opinion
If I'm right, please fix as soon as possible.🙏
I really like Svelte and Svelte kit, and also Skeleton too...

### Steps To Reproduce

1. open popup
2. try to close
3. it has a bit of delay and then closed

**Comment by endigo9740** [comment]
@jin2255 if you'll surround your code blocks in triple backticks at the start and end, it'll format as a code block which will make this easier to read.

**Comment by Sarenor** [comment]
I agree that your variant is more snappy, but I could also see a point where you would want a noticeable delay before closing a popup, so I'd advocate to separate it from the transition time and provide it as a separate attribute in ``PopupSettings`` with a default of 0.
Can't do that in v1 though, because it might be behavior that people rely on, so it's probably an issue for v2 anyways.

**Comment by Sarenor** [comment]
You are correct, that's how it currently works.
But some people might want to actually have that delay and not have the popup vanish immediately.

So we can't just change current behavior, because people might rely on it/want it in their application.

**Comment by endigo9740** [comment]
Hey @jin2255 while we don't have an issue created for this yet - one of our major plans with the next version of Skeleton is to start breaking certain core features of Skeleton (like Popups) into their own standalone packages. These would be installed and usable outside of using Skeleton directly.

You can see this indicated on our roadmap here:
https://github.com/skeletonlabs/skeleton/discussions/1367

![Screenshot 2023-07-14 at 3 43 27 PM](https://github.com/skeletonlabs/skeleton/assets/1509726/66dcf59b-b64e-43ef-8d47-15bdb1983b1b)

While you've filed this ticket as a `bug` I believe this falls more in the category of a `feature request`, so I'll update as such. 

As it stands we're not looking to implement major feature adjustments at this time. Instead, we're fielding all feedback to review and consider for this larger sweeping update in the near future. That said, we've heard your request here and will take this into consideration. But for now any changes are going to be a little ways out.

If you need something sooner I can make a few suggestions:

1. All of Skeleton is open source - which means you can view, clone, and modify the source as you see fit ([source](https://github.com/skeletonlabs/skeleton/tree/dev/packages/skeleton/src/lib/utilities/Popup))
2. The Floating UI library does most of the work for popups - if you need finite control, consider utilizing the library directly for your own custom features

Otherwise we appreciate your patiences in the meantime.

**Comment by Sarenor** [comment]
Your opinion is technically correct. No one's doubting that.

We're just saying that it's something that can't be changed _right now_.

**Comment by endigo9740** [comment]
FYI, as we begin prepping for the new standalone popup package, we're consolidating all known issues for popups into this new thread:

- https://github.com/skeletonlabs/skeleton/issues/1916

Your post will now be closed, but has been referenced in the post linked above. Please note that by doing this, your request is being folded into this larger effort. Please feel free to monitor the linked issue if you wish to track progress on this going forward.
