### ISSUE TITLE
Simpler Popups

### ISSUE THREAD

**Issue by risalfajar** [skeletonlabs/skeleton#1806]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Just wondering, can we adopt the Tooltip system from Flowbite-Svelte? They're much simpler to use. Maybe we can create a `Popup` component that works by default but accept props to customize.

![image](https://github.com/skeletonlabs/skeleton/assets/28381124/10ecaf66-6a4b-4d2e-a3bd-f70d3ac7c9b7)

### What type of pull request would this be?

Enhancement

### Provide relevant links or additional information.

https://flowbite-svelte.com/docs/components/tooltip

**Comment by endigo9740** [comment]
We have plans to revisit popups as part of the v3 release of Skeleton in the future. Any efforts before then would likely interfer with those plans, since this will include moving this feature to it's own dedicated library outside of the Skeleton core:

https://github.com/skeletonlabs/skeleton/discussions/1367

That said, one of the major updates for Skeleton v2 will allow for other Tailwind plugins like Flowbite to run alongside Skeleton. So if you want you'll be able to mix and match between the two libraries if you wish. It might provide a temporary solution. ETA for the firs v2 release candidate is two weeks from tomorrow.

**Comment by risalfajar** [comment]
Okay, thanks for the direction. But would you consider this simpler popups in v3 release?

**Comment by endigo9740** [comment]
FYI, as we begin prepping for the new standalone popup package, we're consolidating all known issues for popups into this new thread:

- https://github.com/skeletonlabs/skeleton/issues/1916

Your post will now be closed, but has been referenced in the post linked above. Please note that by doing this, your request is being folded into this larger effort. Please feel free to monitor the linked issue if you wish to track progress on this going forward.
