### ISSUE TITLE
Autocomplete denylist always blocks at least 1 option after being populated and then emptied.

### ISSUE THREAD

**Issue by stefanuddenberg** [skeletonlabs/skeleton#1812]
### Current Behavior

The Autocomplete `denylist` argument is helpfully dynamic, but the current checks in the `filterByAllowDeny()` function do not handle what may be a common case: the list is at some point populated by some number of elements, but then becomes empty. This means that one element (the last to be removed from denylist) is always denied. My current workaround is to populate the denylist with an empty string when it would otherwise be empty (e.g., `denylist={[""]}`),

### Expected Behavior

The `denylist` argument should allow itself to become empty dynamically and cease denying any options. 

### Steps To Reproduce

Using the `Autocomplete`  component, bind the `denylist` property to a list of elements, and remove them one at a time. You will notice that the last one to be removed continues to be denied.

**Comment by Mahmoud-zino** [comment]
@stefanuddenberg Can you please provide the Skeleton version you are using? we had a fix for a similar issue (#1736) in v1.10.0.
I have tested this with the latest version and it is working as expected. if you still have the issue please provide reproducible code so we can investigate further.

**Comment by kaixiang1212** [comment]
Not sure if this is related to Autocomplete with Input Chip, but I am having the simillar problem on v1.10.0, updated to v0.11.1 still no luck. 

I captured footage from the official website:

https://github.com/skeletonlabs/skeleton/assets/32703443/32293b98-29d7-4fb9-9b33-9f51a2cc2029

Notice how the last value removed does not appear in the Autocomplete option

This was reported and fixed before in https://github.com/skeletonlabs/skeleton/issues/1723

**Comment by Mahmoud-zino** [comment]
@kaixiang1212 Thank you for mentioning this, I have tested this further and found the problem to be:
we are checking the length of the deny/allowed list before filtering, which will work as long as there are items in the arrays.
https://github.com/skeletonlabs/skeleton/blob/18bbab9d6372fcdb27e9c3a0cded3a967783bf5f/packages/skeleton/src/lib/components/Autocomplete/Autocomplete.svelte#L105

I don't think we should check for `array.length`, since reactive statements in svelte are only called when the value change, so even if the condition we implemented evaluates always to true, the function should only be called when the arrays are changed, which is exactly what we need.
(@AdrianGonz97 Can you please confirm or deny this?)

**Comment by AdrianGonz97** [comment]
@Mahmoud-zino Ah, yea that makes sense. To accommodate this, we can instead define `filterByAllowDeny` to accept the two lists as arguments so that the reactive statement triggers correctly.
```ts
function filterByAllowDeny(allowlist: unknown[], denylist: unknown[]) {
	// ...
}

$: filterByAllowDeny(allowlist, denylist)
```

**Comment by Mahmoud-zino** [comment]
@AdrianGonz97 seems good, I will create a PR 👍
