### ISSUE TITLE
card-hover overlays AutoComplete on hover

### ISSUE THREAD

**Issue by royce-mathew** [skeletonlabs/skeleton#1817]
### Current Behavior

Currently when card-hover is set inside the class, it resizes itself on hover but also overlays itself other elements that were originally in front of the card.
[Screencast from 2023-08-02 14-41-40.webm](https://github.com/skeletonlabs/skeleton/assets/114615781/5230090c-d428-49a2-9b6f-8d1f4d362555)

### Expected Behavior

I've tried modifying the z-index of the div holding the AutoComplete component. I don't really know how I can stop the card from modifying its z-index on hover. The card should not be modifying its z-index on hover, instead, it should just be resizing itself.

### Steps To Reproduce

1. Create a AutoComplete Component
2. Create a card that overlays the autocomplete component
3. Add `card-hover` class to the card
4. hover over the card

**Comment by Mahmoud-zino** [comment]
@royce-mathew 
The `.card-hover` class doesn't modify the z-index.
https://github.com/skeletonlabs/skeleton/blob/bb73227b962303ccfd8040223ae42d1397aafda3/packages/skeleton/src/lib/styles/elements/cards.css#L30
this must be the effect of something else, please share reproducible code (Stackblitz) so we can investigate further.

**Comment by endigo9740** [comment]
Animations can sometimes mess with the z-index ordering. It's typically more of a browser bug rather than an implementation issue. Off hand there's nothing obviously wrong or out of place, so a reproduction would be great.

**Comment by royce-mathew** [comment]
Here's a Reproduction: [StackBlitz](https://stackblitz.com/edit/skeletonlabs-repl-jie6fe?file=src%2Froutes%2F%2Bpage.svelte)

**Comment by endigo9740** [comment]
Hey @royce-mathew so looking at your reproduction I see you're handling the overlay styling for your search region yourself. That's fine, but as I mentioned above I believe the issue you're encountering is either CSS or browser specific issue. In this case you have ownership over the styling. There's nothing we can do on our end to help you here since the `.card-hover` style doesn't modify the `z-index` in any fashion, noted in Mahmoud's post above.

As a bit of alternative suggestion here though, I wanted to bring your attention to the fact that Skeleton does provide a popup system:

- https://www.skeleton.dev/utilities/popups

I'll warn you, it's not a trivial add. It requires several steps and an additional dependency in your project for Floating UI. That said, we do provide a specific example for pairing the Autocomplete with Popups here:

https://www.skeleton.dev/components/autocomplete#popup

Again, I can't promise it'll resolve the z-index fighting issue you're seeing, but might be worth a try.

If you can identify anything that might help on Skeleton's end we would welcome a PR and contribution though.
