### ISSUE TITLE
AppBar is not fixed

### ISSUE THREAD

**Issue by devtrix** [skeletonlabs/skeleton#1887]
### Current Behavior

I am using v1.8.  In my +layout.svelte  I have it like this
`
<AppShell>
<svelte:fragment slot="header">
		<CDAppBar {data} />
</svelte:fragment>
....
`
Its still scrolls with the page.  

### Expected Behavior

AppBar should be fixed.

**Comment by endigo9740** [comment]
For most projects we recommend using the Skeleton CLI which has the option to setup the App Shell for you, but otherwise make sure you follow the prereq steps here. It may not work as expected if you don't:

https://www.skeleton.dev/components/app-shell#prerequisites

Skeleton v1.8 released in late June, so if this was a prominent issue I think we would be aware by now from other users. This is likely an issue in your project. Given this I'm going to go ahead and close this issue, but will monitor your response to help troubleshoot if the issue persists.

**Comment by devtrix** [comment]
You are right, I am not sure what happened, it was working.  I just created a new app and it works there so I will copy my code into to it.  Thanks again.
