### ISSUE TITLE
Why is Skeleton v2 restricted to SvelteKit?

### ISSUE THREAD

**Issue by benmccann** [skeletonlabs/skeleton#1892]
### Link to the Page

https://skeleton-docs-git-v2-skeleton-labs.vercel.app/docs/get-started

### Describe the Issue (screenshots encouraged!)

The v2 docs say "Please be aware that Skeleton only supports SvelteKit applications at this time."  From quick glance, I couldn't see anything in the codebase that relies on SvelteKit. Could this warning be removed? If not, it might be nice to expand upon why only SvelteKit is supported and whether that might change in the future

We generally recommend against making libraries SvelteKit-specific. There's no functionality I'm aware of that you couldn't build without knowledge of SvelteKit and we still officially support non-SvelteKit apps such as the apps you get from running `npm init vite`

**Comment by endigo9740** [comment]
Hey @benmccann, great to see you. We appreciate all you do for Svelte and Sveltekit!

To answer your question - technically it's not restricted. We just don't officially provide support for other options. Which includes documenting or answering support questions at this time. Though that's our official stance, but technically we have and do help folks out when this comes up on a rare occasion.

We explained our decision to move away from providing support for these options here back in December:
- https://github.com/skeletonlabs/skeleton/discussions/721

It basically comes down to three things:

1. SvelteKit v1 launched around this time and we saw even the official Svelte docs moving toward SvelteKit
2. We polled usage numbers and SvelteKIt dominated usage for our user base
3. The important one - it was taking a lot of time and effort to test, document, and maintain parity between all options

But know that even right this moment, Skeleton DOES work for these other options. We just don't have the manpower to provide direct support for these extra options. Our plate is already full.

Unlike larger open source projects like Svelte/Kit, Skeleton and our members are not funded. We offer options for folks to donate, a premium store, ads, etc. But none of this really provides more than enough to keep our hosting and other services covered. Everyone here is a volunteer except for me, I'm the only person working full time, and I'll tell you straight up, I'm not taking a cut because we're not earning enough. This greatly limits our scope on the project.

That said, I'm very much interested in changing that if the opportunity provided itself. If you have any advice on how to help in this regard, or if you have contacts that could help us secure real funding. Then we would be more than happy to find ways to expand support, not just for Svelte, but multiple frameworks as well, per our [plans in our roadmap](https://github.com/skeletonlabs/skeleton/discussions/1367). But right now, that's just not a realistic option.

I hope that makes sense.

**Comment by benmccann** [comment]
Makes sense. I wonder if the message could just be tweaked a bit to be clearer. Maybe something like this:

> Please be that Skeleton is only documented and tested in SvelteKit applications due to resource constraints. While Skeleton may work in other Svelte-based applications, no official support is provided.

**Comment by endigo9740** [comment]
Absolutely, we've considered this as well. But we worry that even alluding to compatibility may open the floodgates to more support questions. I mean right now we state we only support SvelteKit and yet we still get plenty of questions about Vite/Svelte, Astro, Tauri, etc.

Support is one of those areas that we really struggle with, just because of the pure volume of it. We get something like 100+ questions a week between Discord, GitHub, and other sources. Yet only about 2-3 of us available to address these. This means a large portion of our day is devoted to support.

Don't get me wrong, I love helping folks and solving issues, but it does limit our capacity for other things - like building the library itself! :)

So again, we've opted to just let is be an unspoken thing for now. If/when someone comes around that wishes to take charge on maintaining the Svelte/Astro/Tauri/etc end of things, we more than welcome that help. But right now, there's no just way we can shoulder that extra effort.

**Comment by benmccann** [comment]
Another option might be to say you support only Vite rather than SvelteKit. The setups should be identical, so wouldn't introduce any additional burden, but would then support both official Svelte templates (`npm init svelte` and `npm init vite`).

**Comment by endigo9740** [comment]
True. Either way I appreciate you bringing this up Ben.

Just FYI I personally led the charge for Vite and Astro support early on - I wanted Skeleton to run everywhere Svelte runs. Unfortunately we had to scale back due to the reasons stated above. However, a lot has changed since December, so perhaps it's time we re-evaluate our options here.

I'll plan to bring this up with our team soon though. We're getting past the hurdle of our new v2 release candidate which dropped this week. But maybe there's a way we can bring back full support for these other options. I think that would be great.

**Comment by benmccann** [comment]
Thanks. Hopefully there's someway to avoid making it sound like it's broken elsewhere without also increasing your support burden. Regardless of what you decide thanks for making Skeleton available! I've seen lots of people talking about it excitedly. I think it's the most starred Svelte UI library now!

**Comment by endigo9740** [comment]
For sure. There's lots we want to do, but the challenge is figuring out reasonable ways to make it all happen within the confines of the resources we have available to us. I'm sure we can figure out a way to make it work.

I appreciate your kind words, really truly it means a lot coming from you sir!

It sounds like the original question has been addressed here so I'm going to close out this thread, but let us know if we can help with anything else!

**Comment by endigo9740** [comment]
Hey @benmccann. I know this is a long closed issue and discussion you've forgot about. But I wanted to ping you about some updates we just revealed for the next major updates for Skeleton. We have an RFC here:

https://github.com/skeletonlabs/skeleton/discussions/2375

By all means, feel free to chip in and share your thought. But I want to specifically highlight that as part of this update, we will be looking to expand our support beyond just SvelteKit. The latest version of SvelteKit will always be included and our personal recommendation, but this will also include:

* Vite + Svelte ("vanilla" Svelte as some folks call it)
* Astro

Likewise, we are lookin to make Skeleton more modular, which see our Svelte-specific features moved to their own package. Alongside this we will also introduce support for React. Which means we're going to aim to support a number of additional React meta frameworks as well. This may include:

* Next.js (for sure)
* Remix
* Vite + React

If you have any other suggestions for meta frameworks we should keep on our radar, please do share. I'd be happy to add this to our internal documentation to review soon.

Thanks again for your suggestion. I know it can sometimes take a bit of time to get the ball rolling, but I do want you to know I take all feedback like this to hear! Thank you sir!
