### ISSUE TITLE
TreeView selection of item

### ISSUE THREAD

**Issue by cesboa** [skeletonlabs/skeleton#1926]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

1) As there is a on:toggle event on a TreeViewItem, should there not be a on:selected or something like that. So it's possible to select a item (not the check  or radio) but the element it self.  I believe a workaround would to use on:toggle or on:click and then do the logic, but a native way would be cool.

2) Is it a bug or feature that on:click propagate twice if the check/radio item is clicked. I tried on click propagation on the radio/check item but that doesn't work.

3) A context (right click) selection event maybe for context menu.

4) sort the tree view - but maybe that is already a thing if it's reactive.

5) A big bonus, native drag drop of items in the view would be really cool!!

Cheers,

### What type of pull request would this be?

New Feature

**Comment by cesboa** [comment]
@endigo9740 Great info, thank you for pointing me that info. I respect the overall goal of Skeleton, thanks for the heads up!

**Comment by endigo9740** [comment]
@Mahmoud-zino if you get a moment can you provide an update about the status of the requested items above. Specifically items 1 and 2.

@cesboa a couple things per the original requests:

> 3. A context (right click) selection event maybe for context menu.

This would be out of scope of this component. Context Menus may be a part of our planned Popup utility updates though:
https://github.com/skeletonlabs/skeleton/issues/1916

> 4. sort the tree view - but maybe that is already a thing if it's reactive.

If you're using the recursive tree view option I believe this is already in your control. It's data-driven, which means you have the source data to control this.

> 5. A big bonus, native drag drop of items in the view would be really cool!!

Not sure what you mean by this, but "drop downs" are typically what we refer to as popups. See the reference to this above, or view the documentation here:
https://www.skeleton.dev/utilities/popups

Feel free to clarify if I've misunderstood these requests.

**Comment by Mahmoud-zino** [comment]
> As there is a on:toggle event on a TreeViewItem, should there not be a on:selected or something like that. So it's possible to select a item (not the check or radio) but the element it self. I believe a workaround would to use on:toggle or on:click and then do the logic, but a native way would be cool.

we don't have selection state / we are not planning to support it because it is out of scope, however using some CSS tricks you could hide the input and change the checked style to appear like a selected element.
this is not yet tested and I expect some issues here but I will aim to test it soon and resolve any issue in this regard.

> Is it a bug or feature that on:click propagate twice if the check/radio item is clicked. I tried on click propagation on the radio/check item but that doesn't work.

this should be resolved in the next update of the tree-view, we already have a solution for the problem but it is not yet implemented because we want to resolve all problems in one place.

> sort the tree view - but maybe that is already a thing if it's reactive.

this is already part of the design, however at the moment we have the issue where changing the object outside the tree is not updating the tree. this should also be resolved in the very near future.

----

I can't help but think all of the requested items will be used to create a folder/file structure, and I know many users are wanting to implement it.
once all bugs are resolved and we have a stable tree-view, I will create a blog post explaining how in details. 👍

**Comment by endigo9740** [comment]
In an effort to prepare for Skeleton v3, we're consolidate some related issues down to a single ticket. This will ensure that we can see the full context of requests when the time comes to refactor and update this feature going forward. If you wish to add additional feedback or suggestions, please so here:

- https://github.com/skeletonlabs/skeleton/issues/2358
