### ISSUE TITLE
stepTerm in <Step> not working as expected

### ISSUE THREAD

**Issue by SK4P3** [skeletonlabs/skeleton#1989]
### Current Behavior

The step term property in <Step> doesn't work. I tried this:

```ts
<Stepper stepTerm='TestStep'>
    <Step stepTerm='OtherTestStep'>
        <svelte:fragment slot="header">(header)</svelte:fragment>
        (content)
    </Step>
    <Step stepTerm='AnotherTestStep'>
        <svelte:fragment slot="header">(header)</svelte:fragment>
        (content)
    </Step>
</Stepper>
```

as specified in the documentation but the Step just shows "TestStep" and not "OtherTestStep" or "AnotherTestStep". Is this an issue or am I doing something wrong

### Expected Behavior

I expect to be able to overwrite the stepTerm for each step seperately.

**Comment by endigo9740** [comment]
@SK4P3 yeah looks like a misunderstanding of how the prop is used in the child items. The source might help:

- https://github.com/skeletonlabs/skeleton/blob/master/packages/skeleton/src/lib/components/Stepper/Step.svelte#L118
- https://github.com/skeletonlabs/skeleton/blob/master/packages/skeleton/src/lib/components/Stepper/Step.svelte#L122

So essentially the only place `stemTerm` is used within the item is in the header/content slot default values. Since you're setting your own header/content slot content this is overwriting this.

You may be expecting `stepTerm` to carry up to the parent Stepper, which is not (and likely never will be) the case.

**Comment by endigo9740** [comment]
That said, we do have plans to revisit the Stepper component in the future. If you have a use case for this, I might suggest adding a note here:

https://github.com/skeletonlabs/skeleton/issues/1780

**Comment by SK4P3** [comment]
Thanks for the answer!
