### ISSUE TITLE
[ProgressBar] Have a text label indicator for the percentage

### ISSUE THREAD

**Issue by sledgehammer999** [skeletonlabs/skeleton#2007]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

I would like a prop to show the percentage as text in the middle of the track.

Design/Look suggestions:
The text color should be the same as the meter color. When the meter covers the text, the (part of the) text that is covered should be in another color. Ideally the color of the track.

Example use case: A file transfer of a big file that takes some time to finish. It would be nice to indicate to the user the percentage done explicitly. Like a download manager.

I have found in the web 2 ways of generally implementing this with CSS, and I'll link them below.
I tried to implement it locally and submit a PR, but I've failed to find a nice way to make the font-size of the text responsive (based on the `height` prop). I mean, I don't know how to set the text to always fit in the track/meter height without involving Javascript.
Unfortunately, I am a total web dev noob and I can't pursue this further on my own.

### What type of pull request would this be?

Enhancement

### Provide relevant links or additional information.

Relevant CSS progress bar examples for the text inversion:
1. Using `clip-path: inset()`: https://stackoverflow.com/a/61353195
2. Using `mix-blend-mode`: https://medium.com/@cachgill/an-improved-color-inverting-progress-bar-20111ec8ced6

**Comment by endigo9740** [comment]
@sledgehammer999 we actually had something like this in an early version of Skeleton, but we opted to remove it because we found it too opinionated and inflexible. Skeleton components are meant to be building blocks, which when combined with other elements and styles provides something specific to your needs.

For example, the position (top/left/bottom/right) and styling might differ greatly between your instance and the next person needs or wants. So for that reason we leave it up to the end users to implement this themselves so they have full control top to bottom.

Thankfully Tailwind makes this fairly easy to control the layout, and the value itself should already be a dynamic value you're providing to your `<ProgrressBar>` component. For example:

```ts
const currentValue = 50;
const maxValue = 100;
```
```html
<div class="grid grid-cols-[1fr_auto] gap-4">
  <ProgressBar label="Progress Bar" value={currentValue} max={maxValue } />
  <span>{currentValue}</span>
</div>
```

Given the simplicity and flexibility of something like this, building this into the component would only serve to bloat and complicate the component, which we're not really keen to do. But I appreciate your request and hope this helps.

**Comment by sledgehammer999** [comment]
I thought it was missing the feature, because the Progress Radials have that.
Your explanation at least makes sense.

Thanks for the example html, but I actually want to show the text overlaid on the progress bar and centered (horizontally).

I quickly hacked this together to overlay and center:
```html
<div class="relative">
  <ProgressBar value={currentValue} max={maxValue } height="h-6" />
  <div class="h-full w-full flex absolute top-0 left-0 items-center justify-center">
    <span>{currentValue}%</span>
  </div>
</div>
```

Now I need to figure out how to handle coloring the text based on if the meter has reached it or not. Like the "inversion" examples I linked. This way it will ensure that it works properly (color-wise) regardless of the skeleton theme chosen.
(just speaking to myself)
