### ISSUE TITLE
Allow passing down classes for chip list of InputChip

### ISSUE THREAD

**Issue by Ynfiniti** [skeletonlabs/skeleton#2052]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Passing down classes for the chip list would enable the developer to alter the styling, overflows etc.

Could be done by making the field `cChipList` accessable, kind of like the `padding` or `rounded` fields already are.

### What type of pull request would this be?

New Feature

**Comment by Mahmoud-zino** [comment]
instead of making `cChipList` accessible I would suggest to use the regionProps just like in the ListBox:
https://github.com/skeletonlabs/skeleton/blob/5b9aab9c55ecd5920b65e908831fb816529366a5/packages/skeleton/src/lib/components/ListBox/ListBox.svelte#L27

This will follow our guidelines and if the user wants to override styles they can do so easily!

@endigo9740 if this sounds reasonable I would be happy to handle it.

**Comment by endigo9740** [comment]
@Mahmoud-zino yeah if there's a region that's currently inaccessible then I'm good with this. I'll assign the ticket to you. Thanks!
