### ISSUE TITLE
Popup doesn't work properly if the button triggering the popup is inside another Svelte Component

### ISSUE THREAD

**Issue by mihai-gabriel** [skeletonlabs/skeleton#2067]
### Current Behavior

```svelte
<!-- ... -->
<!-- Component has <button use:popup={popupSettings}>Click</button> inside it -->
<Component  />
<div data-popup="popup-target-id">Popup Example</div>
<!-- ... -->
```

Clicking on the button inside `Component` will confusingly only work on page refresh, but **not** after navigation between pages using anchors.

### Expected Behavior

Clicking on the button located inside the `Component` should open the popup regardless of any prior 'SPA-like' navigations.

### Steps To Reproduce

1. Click on `Open Popup!` button
2. Observe how the popup opens correctly

Then:
1. Click on `Navigate to Second Page` link
2. Click on `Navigate to first page` link
3. Click on `Open Popup!` button
4. Observe how the popup does not open anymore (unless refreshing the page)

### Link to Reproduction / Stackblitz

https://stackblitz.com/edit/sveltejs-kit-template-default-bmwdfj?file=src%2Froutes%2F%2Bpage.svelte

### More Information

- I have used `npm create skeleton-app@latest my-skeleton-app` to create the Stackblitz reproduction app.

**Comment by Mahmoud-zino** [comment]
@mihai-gabriel This is somewhat expected behaviour because of the order the components are rendered in.
so if we go step by step after navigation: 
1. the component is rendered first because it is a child of the page, 
2. which means the popup is initialized and starts searching for the div, 
3. It finds nothing so it replaces it with an empty div
https://github.com/skeletonlabs/skeleton/blob/0bce0ff302b8a7995bf49bbeeb8d19d8614a2ceb/packages/skeleton/src/lib/utilities/Popup/popup.ts#L23

Now to be honest, I am not sure why it is not behaving like this when refreshing but I am suspecting something with how svelte do the initial page load.

and to solve your problem, you can easily move the popup above the component:
```svelte
<div data-popup="popup-target-id">Popup Example</div>
<Component  />
```

**Comment by mihai-gabriel** [comment]
@Mahmoud-zino Thanks for the insight. Now that you're pointing it out, it does makes a lot of sense since the script inside the component runs when the component first renders. I got confused by the fact that it worked on page load, but as you said, it is probably because SvelteKit pre-renders all the HTML and then hydrates, which makes it so that the Component script is actually run after all the DOM is available.
I have learnt something new today :)

Thanks again and have a nice day!
