### ISSUE TITLE
Long press event on popup

### ISSUE THREAD

**Issue by edrichhans** [skeletonlabs/skeleton#2101]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Allow a new event `"press"` in the `PopupSettings` that triggers a popup when a component is long-pressed. Useful for mobile menus (used together with combobox)

https://github.com/skeletonlabs/skeleton/assets/13763624/8a6b716c-7baa-4547-bbe1-8e7baac686b1

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
@edrichhans we typically discourage "drive by" pull requests, because they often time conflict with existing endeavors and do not leave any room for discussion before the work is completed. Unfortunately this may be effected by both, per:

https://github.com/skeletonlabs/skeleton/issues/1916

> While we prep and plan for this major change, we're going to implement a feature freeze on the current popup. This helps prevent redundant effort and avoids pushing out the goalpost even further

While this certainly sounds like an interesting feature, and it's something I'd like to consolidate into the requests for the next iteration of this feature. I do not believe this is going to be something we move forward with at this time. I'd encourage you please follow our contribution requirements here:

https://www.skeleton.dev/docs/contributing/requirements

![image](https://github.com/skeletonlabs/skeleton/assets/1509726/2911bbaf-5de4-488f-a883-e70033dd0152)

This is shared as part of the checklist when creating a pull request.

**Comment by endigo9740** [comment]
I've linked to this issue in the popup refactor thread. Again, I do hope to borrow ideas from your submission. But as stated above, we cannot move forward with this as this time.

**Comment by edrichhans** [comment]
No worries, thanks for letting me know. Didn't see the refactor going on -- I definitely agree with you. Looking forward to it!
