### ISSUE TITLE
LightSwitch Aspect Ratio Bug

### ISSUE THREAD

**Issue by deancochran** [skeletonlabs/skeleton#2166]
### Current Behavior

After installing @tailwindcss/aspect-ratio, and including the plugin in the tailwind config file. The LightSwitch Component seems to not work as expected

### Expected Behavior

Before Tailwind Configuration with aspect ratio
<img width="142" alt="expected" src="https://github.com/skeletonlabs/skeleton/assets/60753828/6d4be90f-c510-4c1b-b63a-35756fc44227">

Before Tailwind Configuration with aspect ratio
<img width="174" alt="unexpected" src="https://github.com/skeletonlabs/skeleton/assets/60753828/2c6a6116-edae-44bb-a310-530143811619">

### Steps To Reproduce

1. make a skeleton UI project.
2. Import Lightswitch
3. install and configure @tailwindcss/aspect-ratio

### More Information

https://github.com/tailwindlabs/tailwindcss-aspect-ratio

**Comment by endigo9740** [comment]
@deancochran we actually discourage the use of the Tailwind Aspect Ratio plugin. Tailwind talks about the use case for this feature in the plugin readme:

> Tailwind CSS v3.0 shipped with [native aspect-ratio](https://tailwindcss.com/docs/aspect-ratio) support, and while these new utilities are great, the aspect-ratio property isn't supported in Safari 14, which still has [significant global usage](https://caniuse.com/mdn-css_properties_aspect-ratio). If you need to support Safari 14, this plugin is still the best way to do that.

Basically, Tailwind has shipped the aspect ratio feature baked into the core since v3, which released in late 2021. Within the last two years, Safari 14 has dwindled. In fact I'm having trouble even finding any record of it:

https://gs.statcounter.com/browser-version-market-share

Unless you have a VERY specific use case that starts Safari 14 or older, then my recommendation is to drop this plugin. Details for using the new built-in version can be found here:

https://tailwindcss.com/docs/aspect-ratio
