### ISSUE TITLE
No option to disable focustrap on overlays (e.g. listbox modal)

### ISSUE THREAD

**Issue by accesstechnology-mike** [skeletonlabs/skeleton#2260]
### Current Behavior

Within a modal, there is always a white outline of the first option:

![image](https://github.com/skeletonlabs/skeleton/assets/55278705/31abf051-aca5-47f3-ad51-d993d2583ef8)

This seems to be the intended behaviour: https://www.skeleton.dev/actions/focus-trap

> Focusing Overlays
> Skeleton automatically enables this action for overlays such as [modals](https://www.skeleton.dev/utilities/modals) and [drawers](https://www.skeleton.dev/utilities/drawers) to aid accessibility.

### Expected Behavior

I would like someway to disable focustrap, so that all options look the same, except (in my use case) the currently active one.

**Comment by Sarenor** [comment]
For accessibility reasons, Skeleton really does not want to do that and it is indeed intended behaviour.

You can of course always clone the Modal component and remove it from your take on the Modal, but Skeleton itself won't offer that as an option.

**Comment by entrenadorhispano** [comment]
Guys, the focus trap is creating a user-agent focused outline color in mobile browsers. 

Not being able to disable it will only force us to create our own custom modals.

Please check this issue again. Thanks 💯

**Comment by endigo9740** [comment]
@entrenadorhispano two things here:

1. We prefer when folks create new issues, even if you need to reference older issues. Otherwise I'm one of the only people alerted to your message and can easily miss it
2. Modals are working as intended. We follow the ARIA APG guidelines for this: https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/

> When a dialog opens, focus moves to an element contained in the dialog. Generally, focus is initially set on the first focusable element. However, the most appropriate focus placement will depend on the nature and size of the content.

Modals auto-focus the first focusable element within. And focus has a visual style, also to meet a11y guidelines. So again, this is all working as intended. If you wish to have different behavior that breaks a11y guidelines, then you're on your own to implement this.
