### ISSUE TITLE
Select and multiple select for elements in scroll containers

### ISSUE THREAD

**Issue by mircea-milencianu** [skeletonlabs/skeleton#2282]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Would be incredible useful to allow for scroll containers or carousels to have the possibility of selecting 1 or more of its child elements. Binding them to variables would be very nice.

I am not a front-end dev guy but currently I am achieving this with the following piece of code:
```
<ListBox
		multiple
		active="variant-filled-secondary"
		rounded="rounded-md"
		spacing="space-y-0"
		padding="px-1 py-1"
	>
			{#key resetSelections}
				{#each object) as [index, text]}
					<ListBoxItem bind:group={list_variable} name="my_list" value={text}>
						<RedCard text={text} />
					</ListBoxItem>
				{/each}
			{/key}
		</div>
	</ListBox>

```
Which is a bit of a misuse for a listbox but it does the job.

Features to consider:
* multiple select with an upper bound;
* bind to variables prop;
* clear logic when selecting or deselecting elements;

Example:
Multiple select with a max 2 elements.
When a new element is selected it is appended to a list to which is bound.
If more elements than max allow are selected, the first one is removed and the last selection appended to the list.

Thank you and hope its enough! If not I am awaiting your questions if it sparks any interest.

### What type of pull request would this be?

New Feature

**Comment by Sarenor** [comment]
Skeleton usually prefers giving you smaller building blocks to then stick together in whichever way your app needs.
Right now, Scroll Containers are just css to help you achieve carousel-like behaviour and you can put any element you want in there.

So, you could, conceivably have a component that displays an image in the background, with a checkbox rendered at the upper left (or wherever you want it) that gets toggled on image click.
Checkbox handling is up to you that way, it doesn't have to be an image either, could be a card or something else.

**Comment by mircea-milencianu** [comment]
Thanks for the response!

As i mentioned before i am not very knowledgeable with CSS, HTML and TS.
I am using svelte with skeleton because i find it very easy to get stuff done fast and looking sharp.

What you are saying makes perfect sense from the perspective of a frontend knowledgeable dev but I am missing that part and it will take a lot of time for me to get it done properly. You guys on the other hand have already the listbox implementation done.

Also, from my perspective having more features and customization options around these containers can be very useful and unlock more possibilities for creators like me to have stable and consistent components to work with. My custom logic around this will take a lot of trial and error to get right on multiple screens.

Any chance you will consider it?

**Comment by Sarenor** [comment]
I'm just one of the maintainers and an unimportant one at that, so my opinion is just that: An opinion, not a final decision.
It's up to Chris and the others to make a final decision on this.

> Also, from my perspective having more features and customization options around these containers can be very useful
That's why they are so bare bones though. The less logic we put into things, the less logic you have to fight with when wanting to use something for your specific need.

In addition to that, every feature we add is a feature that needs to be maintained, that might - justifiably so - get follow up feature requests that also need to be implemented/maintained, so new additions are considered carefully.

I do get your pain though and can very much understand and emphasize with it. What I can definitely offer you is help: If you find yourself struggling with Skeleton, the Discord's always open and happy to help, as are the discussions on Github.

**Comment by mircea-milencianu** [comment]
Thanks for the insight and I am happy to leave it here and close it as I have drawn your attention to it.

Thank you for all the work you do and who knows, maybe it will get done!
