### ISSUE TITLE
Invalid placement of Event

### ISSUE THREAD

**Issue by Byteingpython** [skeletonlabs/skeleton#2323]
### Link to the Page

https://www.skeleton.dev/components/steppers

### Describe the Issue (screenshots encouraged!)

`on:complete` is a `Stepper Event`, not a `Step` event
![Screenshot](https://github.com/skeletonlabs/skeleton/assets/124276113/fad33c80-2e6c-4f0f-b22f-299497a74c29)

**Comment by phamduylong** [comment]
Seems right. I'll throw in a quick PR for this.

**Comment by endigo9740** [comment]
@phamduylong to be clear, the only change is the `Stepper` text needs to be relabeled `Step` here:
https://github.com/skeletonlabs/skeleton/blob/master/sites/skeleton.dev/src/routes/(inner)/components/steppers/+page.svelte#L19

Please do not change anything else beyond this.

**Comment by phamduylong** [comment]
@endigo9740 That looks kinda weird, just changes every labels to Step. I don't get the idea.

**Comment by endigo9740** [comment]
You're right, after reviewing again, this actually going to be more difficult to fix because of the way Sveld works. The tool we use to automatically document within the components themselves. General idea is Events are handled via JSDoc comments and those self identify where the comments live. This is not manually specified.

So we'll have to alter the location to the events are handled. Keep the dispatcher in the parent, move the custom events up to the parent component, and the JSDoc comments along with it. Then pass the even handler methods down the Context API to the child.

Given the scope of this, I'm going to request you leave this one to me. I have free time for the next few weeks and will be working on Skeleton in a full time capacity. Which means you'll see a lot of movement on pending tickets over the next couple weeks. I'll reassign this now - but thanks for volunteering!
