### ISSUE TITLE
NEXT: File Upload (replaces Button/Dropzone)

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#2386]
## Zag Integration

https://zagjs.com/components/react/file-upload

## Maintainer Requests

The following requests are coming straight from the Skeleton team. These are highly likely be implemented:

- [ ] Let's aim to combine the [File Button](https://www.skeleton.dev/components/file-buttons) and [File Dropzone](https://www.skeleton.dev/components/file-dropzone) into a singular component

## Community Requests

The following requests have come from the community and are under consideration:
 
* n/a

## Bugs and Issues

* Cannot be reset via JS: https://github.com/skeletonlabs/skeleton/issues/2386#issuecomment-1927188114

## Feedback

If you have additional updates or requests for this feature, please do so in the comments section below.

**Comment by Sarenor** [comment]
For some reason, the FileDropzone & FileButtons can't be reset via Javascript, reproduction can be found here: https://github.com/Sarenor/reset-reproduction

A vanilla input can be reset though. It's very confusing, since the forwarded input references seem to be identical (in the sense that they are both forwarded input references)
