### ISSUE TITLE
Toast component error: Cannot read properties of null, reading 'prefersReducedMotionStore'

### ISSUE THREAD

**Issue by thedevbc** [skeletonlabs/skeleton#2442]
### Current Behavior

When using the Toast component, it appears that server-side rendering is trying to read the `prefersReducedMotionStore`. I think line 58 of the Toast.svelte needs to change to check if the browser is there.

The current workaround I found was to wrap the `<Toast/>` component in an `{#if browser}` block.

The behavior I'm seeing is the default 500 | Internal Error page, and then in our node server logs we see the 'cannot read...' error.

### Expected Behavior

Using the `<Toast/>` component should not produce a runtime error trying to read the `prefersReducedMotionStore`. The server should just not read it.

### Steps To Reproduce

Use the Toast component with default properties. Using the node adapter for svelte-kit.

**Comment by endigo9740** [comment]
@thedevbc we'll likely need more details about what you're doing here. Something seems to be off. You certainly shouldn't see that store error just including the toast component. A few things to check

- Verify you're only using a single instance of the `<Toast/>` component in the root layout of your project
- Ensure you've initialized the Toast store [via the steps on the docs here](https://www.skeleton.dev/utilities/toasts#initialize-stores)
- Make sure you're not trying to call this store on the server-side. This should throw a dedicated error though.
- Let us know if you're doing anything with the [prefersReduceMotionStore](https://www.skeleton.dev/docs/transitions#reduced-motion)

If none of the items listed here are relevant, we might need a minimal reproduction to help debug further.

**Comment by thedevbc** [comment]
@endigo9740 Thank you. It appears that we are doing all of the things you mention and we aren't doing anything with the prefersReducedMotionStore. We are using the Toast for error handling, so there is some of our code in place to trigger a toast on an error. I'll investigate further to see if I can narrow it down some. And I'll work on providing an example that reproduces it.

**Comment by RisaI** [comment]
This also happens with the Modal component, had to wrap both `Modal` and `Toast` inside `{#if browser}`.

**Comment by endigo9740** [comment]
@thedevbc @RisaI I'm sorry folks but there's no significant functional changes to the modals/drawers/toasts in several months. If this was was inherent to the features themselves we would be hearing from a lot more people. Until a minimal reproduction can be provided that showcases this error, I'm going to have to chalk it up to an issue with how the features are being setup and used. I'd again encourage you to review the recommendations above. I'd also encourage you to verify you're not yet running Svelte 5 - which is not yet supported (by us or Svelte; as it's not yet ready). 

If you can provide a minimal reproduction, post it here and tag me. I'll be happy to reopen and investigate.

**Comment by szcrow** [comment]
running into this error too after updating from skeleton 2.8.0 to 2.10.0

wrapping the `<Toast />`, `<Modal />` and `<Drawer />` in `{#if browser}` fixes the error

**Comment by szcrow** [comment]
fixed by updating other skeleton related deps (floating-ui/dom, skeleton's tailwind plugin...)

i was so confused, since versions between 2.8.0 and 2.10.0 listed no breaking changes..

**Comment by endigo9740** [comment]
>  i was so confused, since versions between 2.8.0 and 2.10.0 listed no breaking changes..

@szcrow that's because there have been no breaking changes on our end for these features between those releases. In fact I'd venture to say there's been zero changes to those features at all. We catalog all changes here, you can see most of our effort has been focused on Skeleton v3:

https://github.com/skeletonlabs/skeleton/releases 

I'll echo what I said in my previous message above - unless someone can provide a reproduction of the issue, we cannot troubleshoot here. The changes being described would impact a large enough audience that we would be seeing many reports of this was happening to everyone.

Additionally I'll point out the Skeleton v2 doc site always uses the last version of Skeleton's packages. We wouldn't be able to deploy or use these features on the docs if the issue was occurring as described. So something else is at play here.

I'd recommend the following:

1. Verify you've not yet updated to Svelte 5 - as it's not hit a stable release yet
2. Check what other dependencies you may have updated alongside Skeleton - this could be useful information
3. Submit a minimal reproduction of the issue - which would be the most beneficial here
