### ISSUE TITLE
Feature request: Support popular routers like svelte-spa-router and routify 

### ISSUE THREAD

**Issue by boustanihani** [skeletonlabs/skeleton#2527]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Currently the docs state: https://www.skeleton.dev/docs/get-started
`Please be aware that Skeleton only supports "SvelteKit" applications at this time.`

Not everyone uses `SvelteKit`.

Please also support popular routers like `svelte-spa-router` and `routify` :

- https://github.com/ItalyPaleAle/svelte-spa-router
- https://github.com/roxiness/routify

### What type of pull request would this be?

None

**Comment by endigo9740** [comment]
@boustanihani this is already in process. As part of [Skeleton v3](https://github.com/skeletonlabs/skeleton/discussions/2375) we'll introduce support for a whole host of other frameworks and metaframeworks:

- SvelteKit
- Vite/Svelte
- Vite/React
- Next.js
- Remix
- Astro

If you're not using SvelteKit then you're typically running some derivative of Vite/Svelte, which is what I believe Routify is built on.

**Comment by boustanihani** [comment]
Thank you for the quick response and clarifications :)

**Comment by boustanihani** [comment]
@endigo9740 just wondering, is there an expected release date for `Skeleton v3` :) ?

**Comment by Sarenor** [comment]
We're currently sticking with "before the heat death of the universe". I'd be willing to gamble on "Sometime in 2024" as well ;)
Apart from that, not really.

You can also use whatever router-likes you want with Skeleton v2, there _should_ be nothing SvelteKit specific inside of Skeleton since we tried to avoid that.
You're just on your own as far as setup and issues with it go, since we will only _support you_ when you're having issues with SvelteKit.

If it's purely a Skeleton issue, we'll of course help, but if it is a result of your combination of Meta-Framework & Skeleton, you might be on your own (for now).

**Comment by boustanihani** [comment]
Thanks, great work :)

**Comment by endigo9740** [comment]
@boustanihani yeah I completely buried the lede here, but what Sarenor said. Skeleton should be fully compatible with v2 now, we just don't provide support around this - which is what I assumed you were requesting here. That story will change in v3.

As per v3's release, we are working alongside a very much in development version of Svelte, which means the due date is somewhat outside our hands. But we have it good authority that we'll see Svelte 5 drop at the next Svelte Summit. Beyond that, it's just a matter of getting everything done. You can track milestone issues here:

https://github.com/skeletonlabs/skeleton/milestone/5

If I was a betting man I'd say sometime this summer. But you should never trust time quotes from devs! :D
