### ISSUE TITLE
[Skeleton v2] - Light scrollbar is displayed instead of dark one on Opera browser

### ISSUE THREAD

**Issue by laszlo1337** [skeletonlabs/skeleton#2538]
### Current Behavior

Opera browser (and possibly other chromium based browsers) shows light scrollbar in dark mode themes. 
![image](https://github.com/skeletonlabs/skeleton/assets/24696743/9ad5bfbb-de60-4b1a-b78d-6a6408878866)

### Expected Behavior

Should show dark scrollbar as before. 

### Steps To Reproduce

1. Using Opera One(version: 107.0.5045.36)
2. Start skeleton project with darker theme (in my case Vintage)

### More Information
Skeleton v: 2.9.0
As discussed, the issue could be related to recent Chromium engine update 

EDIT: proposed solution does no have effect:
```
:root {
	scrollbar-color: rgba(0,0,0, 1) rgba(0, 0, 0, 0.1); /* thumb / track */
	scrollbar-width: thin;
}
```
Results in:
![image](https://github.com/skeletonlabs/skeleton/assets/24696743/98aa4883-eb8e-4452-83d5-0c49bb6eedc3)

**Comment by endigo9740** [comment]
Thank you for reporting, we'll aim to review asap!

**Comment by Typogram** [comment]
Was looking at the scrollbar issue and potentially I found the culprit.  
Right now in Chrome on Windows I have the square scroll bar with increment and decrement buttons
![image](https://github.com/skeletonlabs/skeleton/assets/41246474/50c453b1-2cea-4a27-aaa4-cec5eedc0b75)

Reset scrollbar-color from any color configuration to auto:
html {
  scrollbar-color: auto !important;
}
restore styled, thin rounded corner scrollbar:
![image](https://github.com/skeletonlabs/skeleton/assets/41246474/ecaab73a-607f-4795-a7cc-9c43bb0cd210)

I thought maybe it is related to this reported issue and could help

**Comment by laszlo1337** [comment]
@Typogram this definitely did work! thanks for the solution ❤

**Comment by jwatts777** [comment]
Adding Typogram's solution works for a fresh install, and the docs site also suffers from this issue.
While working on other things in repo, I found adding the above to main docs site postcss is a quick fix.

**Comment by endigo9740** [comment]
@laszlo1337 sorry it's taken us a bit to get back to this. I think going forward, rather than trying to fight with the vendor-specific prefixes we just go all in on the new standard, that's supported by most browsers these days:

- https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color
- https://developer.chrome.com/docs/css-ui/scrollbar-styling

This is exactly the approach we're going to be using in Skeleton v3. As such, I've prepared a PR with this change:
mind testing this 
https://github.com/skeletonlabs/skeleton/pull/2596

However, myself and the Skeleton team are having trouble replicating your issue. In most browsers we've tested the new standardized are identical to the previous iteration. We think the issue might be a specific combination of Opera plus whatever operating system you're using.

Out of curiosity, would you mind viewing this preview URL to check the display of the scrollbars:
https://skeleton-docs-git-bugfix-scrollbar-display-issue-skeleton-labs.vercel.app/

Compare this to the current production site - which is still running the vendor prefixed styles:
https://www.skeleton.dev/

If possible, screenshots of both would be welcome here!

**Comment by jwatts777** [comment]
@endigo9740
On Windows 10 Home
Chrome (Dark mode) Version: 123.0.6312.106
Preview:
![image](https://github.com/skeletonlabs/skeleton/assets/91865823/88c68ce2-8dff-4098-9b08-5f9cb10eb10a)
Current Prod:
![image](https://github.com/skeletonlabs/skeleton/assets/91865823/6989bc91-0e63-4fa7-9db9-ca5ae3d229f6)

**Comment by endigo9740** [comment]
Thanks Jordon, just for the record we've tested the following browsers:

- MacOS:
  - Chrome
  - Firefox
  - Safari
- Windows:
  - Chrome
  - Firefox
  - Edge
  - Brave
  - Opera

The only outlier so far is that Safari doesn't seem to adhere to the new standards, but we're not going to lose any sleep over this. Safari will catch up eventually, like they always do.
