### ISSUE TITLE
App Shell prevents Safari bottom address bar from collapsing on iOS

### ISSUE THREAD

**Issue by Keagel** [skeletonlabs/skeleton#2560]
### Current Behavior

When scrolling down a page that makes use of the App Shell with Safari on iOS with the address bar set to the bottom, the address bar doesn't collapse as it should normally. That behavior can be observed on the skeleton.dev website right now.

### Expected Behavior

Address bar should collapse

### Steps To Reproduce

1. Implement the default AppShell from https://www.skeleton.dev/components/app-shell
2. Add enough content for the page to be able to scroll

### More Information

https://github.com/skeletonlabs/skeleton/assets/18720666/1cf52959-9a16-4367-844c-b75f8f676606

**Comment by endigo9740** [comment]
@Keagel unfortunately this is one of several known issues with using the App Shell. Basically the App Shell abstracts scroll to a sub-panel within the shell, rather than allowing the entire `<body>` element to scroll. I've created a diagram to help visualize this:

![Screenshot 2024-04-05 at 4 44 29 PM](https://github.com/skeletonlabs/skeleton/assets/1509726/7eeb6d39-f5eb-4240-a411-bae7e2ec8931)

Mobile Safari is setup to hide the bottom panel only when it detects the `<body>` is being scrolled, which of course never happens in the App Shell. This of course introduces the issue with Mobile Safari's bottom floating interface.

You can see some discussion around the topic here:
https://stackoverflow.com/a/75648985

![image](https://github.com/skeletonlabs/skeleton/assets/1509726/6bc46fe5-ee9f-4f9d-b1c4-20e58762a97f)

Sadly I don't think there's anyway to get the behavior you're asking while using the App Shell. Even setting different height values doesn't help here, because the `<body>` never scrolls. For example, you can try something like:

```html
<AppShell class="!h-[100sh]">
	<!-- ... -->
</AppShell>
```

If you prefer the bottom panel to auto-hide on scroll, then I recommend you move away from the App Shell and create your own custom layout which leans into the body scroll. While a bit more effort, it will help avoid some other common App Shell related issues:

- Pull down to refresh not working on mobile (may be Android only)
- Print styles not working as expected
- Plus a few niche a11y issues

Furthermore, given these issues, we're actually taking a pretty hard stance on not bringing the App Shell forward to Skeleton v3. We're going to make the recommendation that folks construct their own custom layouts. That way they can fulfill any requirements they might have.

Hope this helps, and sorry we can't do more!

**Comment by Keagel** [comment]
For now I'm not bothered by the bottom panel staying visible but I'll make the necessary changes since the App Shell won't be coming to v3. Thanks for the thorough answer!
