### ISSUE TITLE
Accordion caret classesControlCaret is repeated on SVG element 

### ISSUE THREAD

**Issue by Keagel** [skeletonlabs/skeleton#2586]
### Current Behavior

Currently, the `classesControlCaret` class is being added to both the SVG element and its parent, but the one on the SVG element isn't interpolated. The behavior is unchanged as the caret still shows and rotates as it should.

Reference:

https://github.com/skeletonlabs/skeleton/blob/9efa96492bbe1f51182f25ee8f4b3ba761591215/packages/skeleton/src/lib/components/Accordion/AccordionItem.svelte#L99

Result:

![CleanShot 2024-04-03 at 11 12 11@2x](https://github.com/skeletonlabs/skeleton/assets/18720666/a8439dbd-6c45-4e9a-907a-4ce8ad1d337f)

**Comment by salisshuaibu11** [comment]
@endigo9740 i would like to take this

**Comment by salisshuaibu11** [comment]
@endigo9740, I've reviewed the svgCaretIcon. Despite correcting the interpolation, the class remains undefined even though "classesControlCaret" is present. The solution was to embed the SVG directly into the HTML without passing it as a variable and utilizing the @html special tags.

![caretIcon](https://github.com/skeletonlabs/skeleton/assets/26380687/426f8042-ba8c-469e-bcc1-ac40b910d430)

**Comment by salisshuaibu11** [comment]
@endigo9740, incorporating the dollar sign label resolved the issue, although I'm uncertain if this is the most efficient approach.

`$: svgCaretIcon = svg`

**Comment by endigo9740** [comment]
@salisshuaibu11 thanks for diving into this. I'd say leave this one to me. I need to dive in an review the full context before I can provide an answer to how we should approach this. And by that time I can probably implement the adjustment directly just as quickly. I'll take all information above into consideration when I get to that point though!

**Comment by endigo9740** [comment]
@Keagel @salisshuaibu11 after reviewing the source directly I see the issue here. It looks like the SVG was abstracted to a [template literal](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) to cleanup the template a bit.

The `class={classesControlCaret}` carried through, even though that should have been removed. You can see the new home for those styles is actively in place here:
https://github.com/skeletonlabs/skeleton/blob/9efa96492bbe1f51182f25ee8f4b3ba761591215/packages/skeleton/src/lib/components/Accordion/AccordionItem.svelte#L183

Given this, the only issue is the fact the remnant use of `classesControlCaret` was not removed from the SVG source.

If for some reason you need access to the SVG element itself, this is already possible using this Tailwind syntax:
https://www.skeleton.dev/docs/styling#tailwinds-arbitrary-variants

For example:

```html
<AccordionItem classesControlCaret="[&>svg]:fill-red-500">...</AccordionItem>
```

Optionally, the Caret icon position is a slot, which means you could replace the open and close icons with custom SVGs, fully styled as desired:
https://www.skeleton.dev/components/accordions#custom-icons

That said, I'll go ahead and submit a quick change to remove the duplicate class on the SVG template literal now to close this out though. This should help avoid further confusion in the future. Expect this to go out as part of the next release of Skeleton v2.
