### ISSUE TITLE
TypeError: mediaQueryList is not a function.

### ISSUE THREAD

**Issue by GianniVullo** [skeletonlabs/skeleton#2656]
### Current Behavior

mediaQueryList API makes skeleton bug on MacBook from 2012.

### Expected Behavior

make use of another API or maybe wrap it in a try catch statement and then choosing a default behavior for reducedmotion ? I'm not sure what's the best strat here

### Steps To Reproduce

0. Using a macOs Catalina machine
1. Using Tauri with SvelteKit and Skeleton Ui
2. initialize everything as described in the doc.
3. Add Toast and Modal
4. typeError:mediaQueryList.addEventListener is not a function

**Comment by endigo9740** [comment]
Just FYI, we've outlined our plans for Skeleton v2 going forward in the post below. I'm am reaching out now as a heads up, as this ticket is slated to be closed when Skeleton v3 is released. Full details can be found here:

- https://github.com/skeletonlabs/skeleton/discussions/3063

If you no longer feel your issue is relevant, please feel free to close it directly.

If you have any questions, please feel free to reach out in the comments below. Thanks!

**Comment by GianniVullo** [comment]
Hello Chris, thank you for your response. It means a lot to me that you took time to answer months after. 

I'm closing the issue rn.
Bye
