### ISSUE TITLE
NEXT Focus ring/border flashes white when switching focus

### ISSUE THREAD

**Issue by TheEisbaer** [skeletonlabs/skeleton#2665]
### Current Behavior

Focus ring/border flashes white, see video

https://github.com/skeletonlabs/skeleton/assets/3662507/46bf0159-948d-4271-8bf0-9016fbc61528

### Expected Behavior

Focus ring/border does not flash

### Steps To Reproduce

1. go to [next skeleton docs](https://next.skeleton.dev/docs/tailwind/forms)
2. have cerberus theme selected (there its the most obvious)
3. switch focus on form elements

### More Information

Chrome Version 125.0.6422.61 (64-Bit)
Windows 11 23H2

**Comment by endigo9740** [comment]
Thanks, we had a similar issue in v2 - but I can't recall how we resolved it. We should be able to compare the v2 stylesheet to v3 and figure it out though. I'we welcome help doing this if someone has time!

**Comment by jaakkonakaza** [comment]
https://github.com/skeletonlabs/skeleton/assets/34682147/27a796b9-3909-43da-bca7-4ce8210ca05d

This seems to be caused by the animation being way too fast. In this video, I changed it to 300ms instead of 100ms. Thoughts? Would it be better to get rid of the whole animation or to make it less noticeable?

`/packages/skeleton/src/plugin/components/forms.css`
```diff
/* Standard Fields --- */

.input,
.textarea,
.select {
	@apply field-outter field-inner;
	@apply border-none;
- 	@apply transition-[all] duration-100;
+       @apply transition-[all] duration-300;
}
```

**Comment by jaakkonakaza** [comment]
https://github.com/skeletonlabs/skeleton/assets/34682147/953cc4e2-f6fd-44a1-ae42-61cee3752312
