### ISSUE TITLE
Theme Generator myCustomTheme

### ISSUE THREAD

**Issue by Bimbimz** [skeletonlabs/skeleton#2815]
### Link to the Page

https://www.skeleton.dev/docs/generator

### Describe the Issue (screenshots encouraged!)

I have followed the guide but get an error message when using myCustomTheme.
there are not enough tutorials on the internet for this.

tailwind.config.js
```
import { myCustomTheme } from './src/styles/CustomTheme'

plugins: [
	skeleton({
		themes: {
			custom: [
				myCustomTheme
			]
		}
	})
]
```

**Comment by Sarenor** [comment]
While I would love to help you, we'd need some more information, like "whats the error message"?

**Comment by endigo9740** [comment]
@Bimbimz we cover themes in detail in our documentation here:

https://www.skeleton.dev/docs/themes

But otherwise what Sarenor said - we need more information about what's happening to help you.

**Comment by Bimbimz** [comment]
this is the error message

```
[plugin:vite:css] [postcss] Cannot find module './src/styles/CustomTheme'
```

file name is CustomTheme.tsx
i changed it to CustomTheme.ts and it works.

is it possible to create a file with the CustomTheme.jsx extension? and what does it contain?

**Comment by endigo9740** [comment]
@Bimbimz that's correct, per our documentation we typically recommend `.ts` files. To make sure we're on the same page:

- `.js` - Javascript file extension
- `.ts` - Typescript file extension
- `.jsx` - JSX file extension (typically used for React components)
- `.tsx` - the Typescript enabled variation of JSX files

There would be no immediate benefit of using JSX for theme files. They're just a JS object that's fed to the Skeleton Tailwind plugin so we can read the settings within.

You linked to the Skeleton v2 documentation which currently only supports Svelte and Sveltekit as mentioned the Get Started docs:

![Screenshot 2024-08-15 at 11 35 18 AM](https://github.com/user-attachments/assets/f8f73972-58d8-4299-804e-b289d39a6dc6)

So let me ask - are you trying to use Skeleton v2 within a React project? If so that's possible, but not officially supported by us. However, we're currently working on developing Skeleton v3, which *will* have full support for React and Next.js. If you're curious about that, you can learn more her:

https://github.com/skeletonlabs/skeleton/discussions/2681

Just note that Skeleton v3 is in an early pre-release state right now and not ready for production use.

**Comment by Bimbimz** [comment]
i want to use the latest version.
i have v2 by running this by default:
npm i -D @skeletonlabs/skeleton @skeletonlabs/tw-plugin

does v3 support Svelte?
i use react a lot, and these days trying svelte.

**Comment by endigo9740** [comment]
Ok, the last release for Skeleton v2 is:

- @skeletonlabs/skeleton: v2.10.2
- @skeletonlabs/tw-plugin: v0.40

You can run `npm list` to verify your installed versions.

For Skeleton v3 - one of the primary goals is to support [Svelte 5](https://svelte-5-preview.vercel.app/docs/introduction), which introduces some new component APIs and features we wish to support. So support will be Svelte 5, React, and eventually Vue and other frameworks as well.

**Comment by endigo9740** [comment]
Also I think the original issue raised has been resolved, so I'll go ahead and close out this issue. If you have further questions feel free to reach out here (I'll see new posts). Thanks!
