### ISSUE TITLE
Code Blocks skeleton v3

### ISSUE THREAD

**Issue by Bimbimz** [skeletonlabs/skeleton#2818]
### Link to the Page

https://next.skeleton.dev/docs/get-started/installation/sveltekit

### Describe the Issue (screenshots encouraged!)

Does skeleton v3 provide code blocks?
not yet in the documentation.
if v3 already supports block code where can i get this like v2:
```
import { CodeBlock } from '@skeletonlabs/skeleton'
and
import { storeHighlightJs } from '@skeletonlabs/skeleton'
```

**Comment by endigo9740** [comment]
@Bimbimz as mentioned previously, Skeleton v3 is in a early pre-release state. This means it's not feature complete. There will be bugs, missing or incomplete features, etc. We're actively updating this to support the new component formats in Svelte and all other adjustments mentioning here:

- https://github.com/skeletonlabs/skeleton/discussions/2681

Per code blocks, we're going in a different direction in v3. Rather than a build-in component, we'll provide an integration guide with popular Shiki syntax highlighter:
https://shiki.style/

However there's nothing stopping you from using this today. They provide instructions on their documentation:
https://shiki.style/guide/install

You can track our progress on this here:

- - https://github.com/skeletonlabs/skeleton/issues/2396

**Comment by Bimbimz** [comment]
OK.
I hope code block is developed first because I think it is a utility that is widely used in almost all types (blogs, pages, docs, forums, etc.)
