### ISSUE TITLE
SvelteKit Tailwind’s layers src: url | skeleton v2 & v3 | SvelteKitError: Not found: /assets

### ISSUE THREAD

**Issue by Bimbimz** [skeletonlabs/skeleton#2819]
### Current Behavior

app.css
```
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";

@layer base {
    @font-face {
        font-family: 'Tes';
        src: url('./assets/font/Tes.ttf');
    }

    body {
        font-family: 'Tes';
    }
}
```

Result:
SvelteKitError: Not found: /assets/font/Tes.ttf

### Steps To Reproduce

app.css
```
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
    @font-face {
        font-family: 'Tes';
        src: url('./assets/font/Tes.ttf');
    }

    body {
        font-family: 'Tes';
    }
}
```

### Link to Reproduction / Stackblitz

https://tailwindcss.com/docs/installation

### More Information

```
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";

to be:

@tailwind base;
@tailwind components;
@tailwind utilities;
```

changing this will fix it, is this behavior normal?

**Comment by endigo9740** [comment]
@Bimbimz can you share how you installed and setup Tailwind that resulted in the invalid directives like this?

```
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";
```

If you're using Skeleton v2, we provide a CLI tool that should auto-implement the directives for you correctly.

If you're using Skeleton v3, our [install instructions](https://next.skeleton.dev/docs/get-started/installation/sveltekit) install Tailwind using [Svelte-Add](https://svelte-add.com/), which again should handle this properly.

> SvelteKitError: Not found: /assets/font/Tes.ttf

I wasn't clear if this was a separate issue - but can you verify you have font files within this path in your application?

**Comment by Bimbimz** [comment]
> @Bimbimz can you share how you installed and setup Skeleton and/or Tailwind that resulted in the invalid directives like this? These are definitely invalid.
> 
> ```
> @import "tailwindcss/base";
> @import "tailwindcss/components";
> @import "tailwindcss/utilities";
> ```

Of course, I did as it was in the document.
I skipped this ~**Create Your Project**~ because I had a project, and did the next step which was:
**Install Skeleton**
```
pnpm i -D @skeletonlabs/skeleton @skeletonlabs/tw-plugin
or 
pnpm i -D @skeletonlabs/skeleton@next @skeletonlabs/skeleton-svelte@next
```
and next: **Install Tailwind** I know by doing this step, my project should not have/should not have tailwind installed previously, because the skeleton has its own version.
```
pnpx svelte-add@latest tailwindcss
or
pnpx svelte-add@latest tailwindcss --tailwindcss-typography false
```
and yes **tailwind.config.js** already in the project without run `npx tailwindcss init`.
but i have `src/app.css` which is automatically filled in it
```
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";
```
> I wasn't clear if this was a separate issue - but can you verify you have font files within this path in your application?

Of course

**Comment by endigo9740** [comment]
Also @Bimbimz just FYI we've received notice of a bug within the dependencies for our most recent release of Skeleton (on Tuesday). You may encounter this when you start importing Skeleton components:

```
Cannot find module '@zag-js/accordion' imported from 
```

We have a fix in place and will be aiming to roll out either tonight or early tomorrow. This should be live shortly after this PR is merged if you wish to track the progress:
https://github.com/skeletonlabs/skeleton/pull/2822

**Comment by Bimbimz** [comment]
> and next: Install Tailwind I know by doing this step, my project should not have/should not have tailwind installed previously, because the skeleton has its own version.

> We do not bundle Tailwind itself. That is always a separate dedicated installation process. We recommend Svelte-Add because it's mostly plug-and-play. It does a few things:
> 1. Installs the Tailwind dependency
> 2. Adds and configures your tailwind.config
> 3. Implements an `app.pcss` global stylesheet (note: the extension may differ)

yes that's what I mean by the word (its own version).
installing with its own version settings (not a modified third party version).
I haven't installed tailwind and use:

```
pnpx svelte-add@latest tailwindcss
or
pnpx svelte-add@latest tailwindcss --tailwindcss-typography false
```

to avoid conflicts with pre-existing (tailwind.config etc) changes

**Comment by endigo9740** [comment]
You've mentioned this a couple times...

> I skipped this because I had a project, and did the next step which was: Install Skeleton

> to avoid conflicts with pre-existing (tailwind.config etc) changes

If I'm understanding, you're trying to installed Skeleton v3 into a pre-existing SvelteKit application that already had Tailwind installed? Is that correct? If so that may be a portion of the issue here. Our documentation is written with the assumption you're creating a brand new project from scratch.

While we do have you scaffold a SvelteKit application, we're assuming the Tailwind configuration in a particular manner - which includes those `@tailwind` directives. If you installed Tailwind yourself, through whatever means you did this, then we're not responsible if this is misconfigured. Does that make sense?

It would be my recommendation that you create a new fresh project following our instructions specifically. Then use that as a reference if you need to update your project settings to match. If not porting your app into the new project itself. Otherwise we cannot guarantee things are setup properly.

**Comment by endigo9740** [comment]
@Bimbimz I've reviewed this with the team and we tested a new project using Svelte-Add. Sure enough we're getting this format for the Tailwind directives:

![image](https://github.com/user-attachments/assets/59bd793e-eb10-4830-9506-4f774c36d278)

However, I've now learned this is valid - just a new format that Tailwind is migrating towards:
https://tailwindcss.com/docs/functions-and-directives#config

So those are valid and you should not need to change. In fact I'd suggest rolling that change back.

Our current thought is your issue lies within the font configuration itself. The issue may actually exist for either directive configuration, but it's being suppressed when you use the older `@tailwind` directive approach. It's should be easy to confirm this by reviewing your app and ensure the font actually renders or not.

That said, we've noted you're referencing your font from this path:

```
src: url('./assets/font/Tes.ttf');
```

However this would be incorrect. SvelteKit has a specific reserved `/static` directory in the project root. You do not reference this when referencing the path though:

```
src: url('/font/Tes.ttf');
```

So `/fonts/Tes.ttf` would actually be referencing a file located in: `<root>/static/fonts/Tes.ttf`

If you can please make both corrections and see if that helps.

**Comment by endigo9740** [comment]
I'm going to go ahead and close this since there's not been a response in a while. I'm happy to reopen if the issue persists.
