### ISSUE TITLE
Expand documentation around Color Paring utility classes

### ISSUE THREAD

**Issue by lendle** [skeletonlabs/skeleton#2845]
### Describe the Issue (screenshots encouraged!)

See #2096 and related issues. 

Unless I missed it, the docs don’t mention this. It would be helpful if they covered it.

**Comment by zawa999** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by endigo9740** [comment]
I know this was reported as a Skeleton v2 issue, given the mention of "tokens". Just FYI we now refer to these as (Skeleton provided) "utility classes" in v3 to be more semantic and accurate. The only utility classes where opacity is relevant is color pairings.
https://next.skeleton.dev/docs/design/colors#pairings

We already have plans to expand the documentation and better explain this feature soon, so we'll keep this ticket as a reminder to do so. Skeleton v2 (due to it's dependency on Svelte 5) is a dead end path, so we will likely not retroactively update the v2 docs for this.

The new docs will be considered the "fix" here.

**Comment by endigo9740** [comment]
Folding this under a larger issue: https://github.com/skeletonlabs/skeleton/issues/2900
