### ISSUE TITLE
Documentation: https://svelte.dev/tutorial/dom-event-forwarding does not exist

### ISSUE THREAD

**Issue by nullpointerexceptionkek** [skeletonlabs/skeleton#2935]
### Link to the Page

https://www.skeleton.dev/docs/contributing/style-guide

### Describe the Issue (screenshots encouraged!)

The documentation links to an invalid Svelte tutorial URL
https://svelte.dev/tutorial/dom-event-forwarding

**Comment by endigo9740** [comment]
Thanks @nullpointerexceptionkek, obviously the big Svelte 5 update for their documentation has modified a few URLs. Thankfully they still have the v4 docs for reference.

For example:

- This will fail: https://svelte.dev/tutorial/dom-event-forwarding
- But this should work: https://v4.svelte.dev/tutorial/dom-event-forwarding

> NOTE: Just adding a subdomain of "v4"

So the fix can either be looking at the location for this information in the new docs, or hardcoding this to the v4 version. I'd assume the latter would be preferable since Skeleton v2 was built with Svelte 4 in mind.

Additionally, the team and I's focus is fully on Skeleton v3 between now and launch, then the v2 docs will be available, but in an archived state. So if this is a change you would like to see, then a PR would be welcome please!
