### ISSUE TITLE
Incorrect button press animation on mobile

### ISSUE THREAD

**Issue by Stef-00012** [skeletonlabs/skeleton#2942]
### Current Behavior

Even if the button is rounded, the press is rectangular

### Expected Behavior

The press should follow the button shape

### Steps To Reproduce

Create a rounded putton and press it on mobile

### Link to Reproduction / Stackblitz

There is an example directly on https://www.skeleton.dev, any rounded button there

### More Information

https://github.com/user-attachments/assets/d46ac39b-9754-4f8d-9fe3-3fd473944237

**Comment by endigo9740** [comment]
Hey @Stef-00012, we actually talk about this here:

https://www.skeleton.dev/elements/core#mobile-focus

Mobile focus states are built into the browser. Skeleton doesn't set them, we merely set a neutral color tone. The default is typically blue in Chromium-based browsers. They don't adhere to border radius styling as you've presented here. Not sure there's anything we can do about that.

It's an a11y-minded feature, so it's typically recommended to leave them on.

If you have any follow up questions let me know, but otherwise I don't think there's anything actionable on our side here.
