### ISSUE TITLE
Combobox does not show results with `multiple`

### ISSUE THREAD

**Issue by MrVauxs** [skeletonlabs/skeleton#2963]
### Current Behavior

Combobox does not fill the input with the selected choices if `multiple` is enabled true. 

This also inadvertently causes `required` to always cause the input to fail the check.

### Expected Behavior

Combobox filling the input with the given array, would be nice to be able to provide a function for the separator used (so you can have something like `x, y, and z` instead of plain `.join(", ")`.

### More Information

Earlier Discord Report for History: https://discord.com/channels/1003691521280856084/1191790107867488316/1303464712981184584

**Comment by endigo9740** [comment]
FYI I noticed this too when testing the feature originally. It's always possible I was doing something wrong. But if not, then that indicates it may be a bug on Zag's end and would need to be reported upstream. Let's review first to confirm, but just a heads up!

**Comment by MrVauxs** [comment]
> FYI I noticed this too when testing the feature originally. It's always possible I was doing something wrong. But if not, then that indicates it may be a bug on Zag's end and would need to be reported upstream. Let's review first to confirm, but just a heads up!

I checked, the official React Zag StackBlitz instance works with `multiple` once you add it to the controls.
https://zagjs.com/components/react/combobox#methods-and-properties

**Comment by MrVauxs** [comment]
> @MrVauxs can you expand on what you mean by "controls". Unfortunately your Stackblitz is non-functional for me. Just links to their homepage.

Oh, the stackblitz is supposed to be what is linked on the Zag page.

And what I meant is that the StackBlitz example Zag has just doesnt have `multiple` (amongst many other stuff) as an available `ComboboxProps` property.

**Comment by endigo9740** [comment]
I'm still completely lost here. `multiple` is a feature that Zag supports. Here it is in their documentation:
https://zagjs.com/components/react/combobox#selecting-multiple-values

But when implemented on our component, it's not working. Which is why this ticket was all about, correct?

**Comment by MrVauxs** [comment]
> FYI I noticed this too when testing the feature originally. It's always possible I was doing something wrong. But if not, then that indicates it may be a bug on Zag's end and would need to be reported upstream. Let's review first to confirm, but just a heads up!

_You weren't sure if this was a bug in Skeleton, or a bug in Zag. I was confirming that it is Skeletons, with an added comment about Zag's official example having outdated types but nonetheless working._

**Comment by phamduylong** [comment]
I'll take a look at ZagJs's StackBlitz to see how they got the behavior working.

**Comment by endigo9740** [comment]
@MrVauxs @phamduylong so two things with this...

First, the feature was filed as a bug ticket - which is fine. But does not adequately summarize the changes required. In short, a bug would imply we implemented something incorrectly or it's not behaving as expected. However this is not the case. The feature is working as expected, but the ability to support `multiple` would require additional effort and a redesign of the UI to support this. As such, I'm adjusting the label from `bug` -> `feature request`.

Second, as a feature request, it's at our discretion if we decide to support the requested feature. And while there's certainly a use-case for a multiple-selection combobox type interface. I feel like it overlaps with another primitive we already provide - the [Tags Input](https://next.skeleton.dev/docs/components/tags-input/react). So in order to support multiple-selection in the Combobox this would require essentially recreating the Tags Input within the Combobox component. I think this is beyond the scope of what we intend for these temporary component features - so I'm going to deny this for now. (Even though Long did a great job with his attempt at this!)

You can read my full thoughts as to why here: https://github.com/skeletonlabs/skeleton/pull/3008#issuecomment-2529168677

So for now, what I'm going to do instead is update the component and documentation to remove the `multiple` feature. I know it's not going to be the preferred option, but this type of interface WILL be supported in the future when we have either:

1. Floating UI Svelte completed and available
2. The native Popover API available

So other words, we will support something like this. Just not *yet*.

**Comment by endigo9740** [comment]
You can see the change here. This will be part of the next release: https://github.com/skeletonlabs/skeleton/pull/3033

Again, if I can provide more context around the long term plans here, let me know.
