### ISSUE TITLE
Progress ring spins too fast

### ISSUE THREAD

**Issue by liamwh** [skeletonlabs/skeleton#2973]
### Current Behavior

Progress ring spins too fast

### Expected Behavior

It should look [like it does on the docs site](https://next.skeleton.dev/docs/components/progress-ring/svelte)

### Steps To Reproduce

```html
<script lang="ts">
    import { ProgressRing } from '@skeletonlabs/skeleton-svelte';
</script>

    <ProgressRing
        value={null}
        size="size-14"
        meterStroke="stroke-tertiary-600-400"
        trackStroke="stroke-tertiary-50-950"
    >
    </ProgressRing>
```

![image](https://github.com/user-attachments/assets/f9e8e286-d813-4018-bf9b-f4ed04f698b0)

### Link to Reproduction / Stackblitz

https://discord.com/channels/1003691521280856084/1191790107867488316/1307984229048647724

**Comment by Hugos68** [comment]
I think the issue is on your side, perhaps an extension or something?
It works fine when reproducing in stackblitz: https://www.sveltelab.dev/k1plh3x5eg1tml9

**Comment by endigo9740** [comment]
@liamwh yeah we'll need more information here. We use the stock spin animation provided by Tailwind itself. 
https://github.com/skeletonlabs/skeleton/blob/next/packages/skeleton-svelte/src/lib/components/ProgressRing/ProgressRing.svelte#L49

This will need to be exposed as a style prop, but otherwise it's pretty straight forward how it works:

- If there's a null value -> enter indeterminate mode
- If indeterminate mode -> apply the spin class

**Comment by liamwh** [comment]
Thanks for the swift response! I understand the API (very intuitive 👏), just not why mine is spinning so fast. 

I'll take a look into it further when possible. Feel free to close and I can re-open if necessary.

**Comment by endigo9740** [comment]
Sure @liamwh if you can provide us steps to replicate we would be happy to take a look! As others pointed out on Discord, it could be related to a particular browser - so maybe cross check? But I certainly have seen that one come up yet!
