### ISSUE TITLE
Add SvelteKit link options to navigation components when in anchor mode 

### ISSUE THREAD

**Issue by MrVauxs** [skeletonlabs/skeleton#2989]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Navigation components can have a `href` property added to them that makes them into anchors. Problem is that you cannot add SvelteKit's link options to these anchors, causing in behavior that may not be wanted.

Given this is a SvelteKit specific feature, this might be better worded as allowing arbitrary properties to be added to Navigation components, but that sounds like a taller order 🤔

### What type of pull request would this be?

Enhancement

### Provide relevant links or additional information.

https://svelte.dev/docs/kit/link-options

**Comment by endigo9740** [comment]
@MrVauxs so these settings cascade or waterfall. Meaning if you set the data attributes on a wrapping parent element, all children within will adhere to the setting. In fact I believe the `sv` CLI's default configuration applies this preloading capabilities to the `<body>` element. Which means full coverage for the entire app by default.

If by chance someone wants to localize these, they can, they'll just need to do it on a wrapping element. I'd recommend this approach as I'm not sure the order of operations here. If SSR is enabled for example, it may be better to apply these to a "fixed" element on the page, rather than dynamically rendered component template.

**Comment by MrVauxs** [comment]
You are right, a wrapper is the most appropriate option here. That solves my problem. Given the warnings about elements not being able to have certain properties I forgot that these options cascade.
