### ISSUE TITLE
Option to hide first/last buttons for Pagination's alternative UI

### ISSUE THREAD

**Issue by knd775** [skeletonlabs/skeleton#2993]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

The first and last page buttons here should be optional. 
![image](https://github.com/user-attachments/assets/ee877a54-46dd-4074-ae13-16b9a2ae9805)

Also, maybe consider automatically hiding them when there are only two pages.

### What type of pull request would this be?

None

**Comment by rxhul18** [comment]
assign

**Comment by endigo9740** [comment]
Go for it @rxhul18. If you have any questions about our contribution process you can see our guidelines here:

https://next.skeleton.dev/docs/resources/contribute

**Comment by endigo9740** [comment]
Just FYI I've closed the PR as the changes were implemented on the v2 branch - even though the requested feature already existed there. Any issue tagged with the v3.0 milestone needs to be done against the `next` branch and agains the v3.0 version of the Pagination feature.

I'm welcome to Rahu doing this, otherwise this still an open issue.

**Comment by phamduylong** [comment]
I assume a `showFirstLastButtons` is sufficient here 🤔 And it goes with alternative interface only I think? Any input? @endigo9740

**Comment by endigo9740** [comment]
@phamduylong double check what we used for v2 and match that please. But should be the same general concept as that.

**Comment by knd775** [comment]
Solved by #3007, closing
