### ISSUE TITLE
React Ratings component missing unique key for loop

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#3037]
It looks like the React version of the [Ratings component](https://next.skeleton.dev/docs/components/rating/react) is throwing an issue regarding [a missing unique keys](https://react.dev/learn/rendering-lists#keeping-list-items-in-order-with-key).

Best I can tell, there is a `key` set, but perhaps it's not unique?

- https://github.com/skeletonlabs/skeleton/blob/next/packages/skeleton-react/src/lib/components/Rating/Rating.tsx#L83

If someone picks this up before me - please let me know if you have any issue replicating this issue in the dev environment.

**Comment by phamduylong** [comment]
I'll try to reproduce it in my local setup. Will investigate it further if the issue happens for me, else I will write here if I don't get it going.

**Comment by endigo9740** [comment]
Thanks Long! If you have any trouble I can circle back to this one tomorrow.

**Comment by phamduylong** [comment]
> Thanks Long! If you have any trouble I can circle back to this one tomorrow.

I'm certainly no expert in React (never built anything with it, in fact) but I think [the PR](https://github.com/skeletonlabs/skeleton/pull/3043) has some potential to solving the issue. I'm having the same key issue when testing in my local setup, but for Popover so that might be worth checking out as well.

![image](https://github.com/user-attachments/assets/ce2277c7-72ec-49c6-bae6-61357006343d)

**Comment by endigo9740** [comment]
@phamduylong saw the PR first, but that makes total sense. I'm new-ish to React as well and didn't think about the empty element being taken into account here.

As per Popovers, feel free to sent a follow up for that as well if you wish to take a look. Otherwise we can log that and get that asap. Thanks for the heads up!
