### ISSUE TITLE
Skeleton CLI

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#552]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

This will be an interactive CLI application that allows you to scaffold and create a new Skeleton project.

@niktek has already made a lot of progress with this. The goal will be to get a version up and running that can be used by a set of beta tests. Perhaps as a public beta.

Nik has notified us that the first draft will most likely include support for SvelteKit only. But this is fine as this covers the wide majority of our users. Support for Vite and Astro can be investigated later.

### What type of pull request would this be?

New Feature

### Any links to similar examples or other references we should review?

@endigo9740 will be creating the initial welcome page(s):
- https://github.com/Brain-Bones/skeleton/issues/551

This will build off the work of both Nik and Fig:
- https://github.com/Brain-Bones/skeleton/issues/296

**Comment by endigo9740** [comment]
@niktek Either subscribe or write a comment here so I can assign to you please.

**Comment by niktek** [comment]
- [x] ~~Add support for Astro~~ - deferred
- [x] ~~Add support for Vite~~ - deferred
- [ ] Add help screen for all cli options
- [ ] Add `ora` spinner for working portion
- [ ] Make the next steps portion more clear
- [ ] Colorise framework choices 


| create-svelte 	| create-vite 			| create-astro 		| create-skeleton-app
| --- 				| --- 					| ---	 			|---
| Directory 		| Name					| Directory			|
| Svelte template 	| Framework				| Astro template	|
| Types (TS/JS/None)| Variant (TS/JS/SK) 	| Install deps ?	|
| ESLint			|						| Init git ?		|
| Prettier			|						| TS strictness		|
| Playwright		|						|					|

# Notes
## create-svelte
- no argv support
- has entry point to call into
- outputs links to add-ons like eslint-plugin-svelte3
- happily blows away existing folders
- `Stuck? Visit us at {discord}`

## create-vite
- no argv support
- no entry point to call into
- uses cross-spawn to launch pm install
- has embedded templates for svelte
- conventional-changelog-cli
- simple-git-hooks lint-staged

## create-astro
- supports argv, but no help screen to show what the options are.
- argv support only pre-selects, still forces display of prompts
- no entry point to call into
- execa instead of spawn
- uses changeset
- pnpm only
- use astro-add for adding tailwind (if it can keep quiet)

**Comment by endigo9740** [comment]
Mentioned this on Discord - but applying it here as well so it doesn't get lost in the shuffle. We'll need a get a version of the CLI repo moved to the new org asap. This is a hard requirement before the big announcement this upcoming week.

**Comment by niktek** [comment]
Beta is out, code is in the org repo.  Other improvements will come with feedback, updates from upstream and migration back to TS
