### ISSUE TITLE
Extra Small option for UI components

### ISSUE THREAD

**Issue by nonan-io** [skeletonlabs/skeleton#572]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

I feel like all UI components of skeleton are quite large. Just for reference the small toggle of skeleton is larger than the standard size toggle provided by tailwind components. Therefore, I'd love to see an extra small option. I mean all large components are so absurdly large that I cannot imagine who would use that.

Is there another way of scaling everything down that I'm not aware of?

**Comment by endigo9740** [comment]
@nonan-io can you provide some examples of where the sizes are "absurdly large" please. Also are you taking into account touch access for touch screen, because like every other major UI library out there, our goal is to support mobile web as well as keyboard/mouse users.

Google has the following recommendation:
https://support.google.com/accessibility/android/answer/7101858?hl=en#:~:text=Consider%20making%20touch%20targets%20at,touchscreen%20objects%20is%207%2D10mm.

Our default buttons, inputs, radio groups are around 40px tall, so actually a bit smaller than this recommendation. Plus some touch-focused UI, such as buttons, do feature a smaller size for users focusing purely on mouse users.

I'll also issue a friendly reminder that nearly every feature is customizable, including the ones mentioned above. If Skeleton's defaults are not adequate for your use case then you may want to consider creating your own reusable options. You can view how we create button sizes here for example:

https://github.com/Brain-Bones/skeleton/blob/master/src/lib/styles/elements/buttons.css#L29
