### ISSUE TITLE
Modal does not trap focus when Shift + Tab is used

### ISSUE THREAD

**Issue by bennymi** [skeletonlabs/skeleton#596]
### Current Behavior

When using a modal the focus is trapped to the modal when tabbing through the components. When going backwards with <kbd>Shift</kbd> + <kbd>Tab</kbd> however, the focus is no longer trapped and we can focus elements behind the modal.

### Steps To Reproduce

1. Go to https://www.skeleton.dev/utilities/modals
2. Click on a modal
3. <kbd>Tab</kbd> through the components (focus is trapped)
4. <kbd>Shift</kbd> + <kbd>Tab</kbd> through the components (focus is not trapped)

**Comment by endigo9740** [comment]
Thank you Benny. I actually ran out of time when implementing this per the release this went live. This has been on my mental checklist since then, but thank you for creating a proper ticket for it finally. We'll aim to get this fixed up soon, otherwise I'd welcome a PR if you willing and able! Thanks!

**Comment by bennymi** [comment]
@endigo9740  I think I solved the bug. I never contributed to open-source however so maybe there were some steps I missed when following the contribution guides. Let me know if I missed something.
