### ISSUE TITLE
Customizing tailwind theme breaks postcss build

### ISSUE THREAD

**Issue by rhinodavid** [skeletonlabs/skeleton#630]
I'm experiencing this on Vite + Svelte, but I expect it applies to SvelteKit as well.

After following the installation instructions start-to-finish; everything works.

Now, I follow the [tailwind instructions "Customizing your theme"](https://tailwindcss.com/docs/font-size#customizing-your-theme). My config now looks like (note the `huge` font size):
```ts
const config = {
  darkMode: "class",
  content: [
    "./src/**/*.{html,js,svelte,ts}",
    require("path").join(
      require.resolve("@skeletonlabs/skeleton"),
      "../**/*.{html,js,svelte,ts}"
      ),
    ],
    theme: {
      fontSize: { huge: "8rem" },
      extend: {},
    },
    plugins: [require("@skeletonlabs/skeleton/tailwind/theme.cjs")],

};
```

Vite outputs:
```
[vite] Internal server error: [postcss] /Users/rhinodavid/my-app/node_modules/@skeletonlabs/skeleton/styles/tailwind.css:9:1: The `text-3xl` class does not exist. If `text-3xl` is a custom class, make sure it is defined within a `@layer` directive.
```

I'm not sure if this is "working as intended", i.e. once you add Skeleton you can't then go back and modify tailwind themes manually, but this bug was very confusing and took a while to run down so I wanted to create the issue to help others that might run across this.

**Comment by endigo9740** [comment]
Hey @rhinodavid, thanks for reaching out.

I have a idea about what's happening here. The Tailwind config is not very intuitive and trips a lot of folks up. If you set the values in the `theme` root object, like you've done, then you're essentially overriding the defaults. Our project relies on these, which is why you see the issue about `text-3xl`. That's a standard Tailwind utility class.

However, you can see how we avoid this in our plugin, which follows a similar structure:
https://github.com/skeletonlabs/skeleton/blob/dev/tailwind.config.cjs

Essentially you'll want to do this:
`theme -> extend -> add custom classes here`

This then EXTENDS each category of styles, rather than replacing them. Let me know if that works and feel free to close out the issue if this resolves the problem for you.

**Comment by rhinodavid** [comment]
Thanks! I figured it was something like that. Is there some troubleshooting method I missed? Nothing in the trace indicated the error was in the tailwind config.

**Comment by endigo9740** [comment]
Glad to hear!

Unfortunately that's the nature of Tailwind right now. I've been using it since February and there's a lot you have to figure out with trial and error. That said, Tailwind v4 is apparently in progress, so hopefully that'll improve some things! One can hope!
