### ISSUE TITLE
It is not possible to apply the styles of the @tailwindcss/typography plugin together with Skeleton.

### ISSUE THREAD

**Issue by bySabi** [skeletonlabs/skeleton#671]
### Current Behavior

I have created two minimal examples. One only `Tailwind` and another with `Tailwind-Skeleton`

For this example, `mdsvex` is used to import a Markdown document as if it were a `Svelte` component.
Then various `prose` utility classes defined in `@tailwindcss/typography` are applied.

The example with `Tailwind` works correctly.
But in the example with `Tailwind-Skeleton` the classes applied to the paragraphs, font size, ... are not applied.

### Steps To Reproduce

Shared Github repo here: https://github.com/bySabi/sveltekit--tailwind-skeleton--example-repos

**Comment by endigo9740** [comment]
@bySabi There's a number of items to consider here, so I'll try to run through each one.

In your repro project, when I try disabling and re-enabling the various styles in your root page style block I'm definitely seeing the styles change. So the prose styles are both active and working, even if the styles are not to your preference right away.

However, looking at your markdown source, you really only have H2 headings and paragraph text to compare against, but in your style's your styling block quotes, and anchors, and all kinds of stuff. This is a bit hard to read, so first off I suggest using multiple @apply statements like we do in our stylesheets. That way you can break your styles into small groups and keep them organized and test one-by-one.

https://github.com/skeletonlabs/skeleton/blob/dev/src/lib/styles/elements/buttons.css#L14

But more specific to you issue, I think you're just simply running into a clash of style inheritance. You're expecting the Tailwind Typography prose styles to automatically precedence, but that is not how this works in practice. We provide some tips on this issue at the bottom of this page, under "Customizing Styles"

https://www.skeleton.dev/guides/styling

> TIP: in some cases you may need to use ! [important](https://tailwindcss.com/docs/configuration#important-modifier) to give precedence, or style both the light/dark mode variations.

Most of the Skeleton's built-in typography styles are set for both light and dark modes. However, reviewing most of your styles, you're only styling the base style (there's no `dark:` variation).

And per your repro you don't seem to have your app configured for light/dark mode at all. We strongly recommend you do configure your project for this, even if you only opt for light or dark modes for your end product. This can be fixed by doing two things:
 
 1. See our config for adding the `darkMode: 'class'` [on this page](https://www.skeleton.dev/guides/tailwind).
 2. If you wish to default to dark mode, add `class="dark"` to the HTML element in `app.html`. [See an example](https://github.com/skeletonlabs/skeleton/blob/dev/src/app.html#L2).
 
 All this said, I think really you're biggest issue is that perhaps the Tailwind Prose styles might not be the right tool for the job here. The goal with the TW plugin add styling to content from an external source that's may not be styled by default. However, with Skeleton, if you're using `all.css`, your content WILL be affected and styled by this stylesheet, because it contains a set of standard typographical styles built in. So you have two choices here:
 
 1. You can consider importing only the stylesheets you need and want from Skeleton manually (I can walk you through this, but know it's not simple and requires a lot more manual maintenance)
 2. Drop the TW prose plugin and lean into the Skeleton typography as the defaults, but customize, override, and extend as you need to.

Option #2 would be my personal recommendation. Here's a quick example of what that might look like. If I remove all prose styles from the root page and then drop the following into the global stylesheet (`app.postcss`)

```css
article {
  @apply max-w-4xl;
}

blockquote:not(.unstyled) {
  @apply border-l-gray-500 bg-gray-200/10 px-4 py-2 italic;
}
```

Even with just a couple small adjustments to the blockquote you can already see the style overrides applied:

![Screen Shot 2022-12-11 at 11 12 48 AM](https://user-images.githubusercontent.com/1509726/206918180-529ec14e-b6f8-4d03-b4f4-a27192b8b116.png)

If you're wondering why I'm including the `:not()` bit, this is to match the exact class I'm overriding from the source here:

https://github.com/skeletonlabs/skeleton/blob/dev/src/lib/styles/typography.css#L54

I literally copied that over, deleted the current styles, and then began writing my overrides. I was then able to see those reflected immediately. Let me know if this approach works better for you.

**Comment by bySabi** [comment]
Wow!!

A wonderful and extensive answer Chris. Thank you!

I am a newbie with `Tailwind` and therefore with `Skeleton` so I am going to take my time to reread your recommendations.

I agree with your recommendation (Option #2). About creating a custom theme. My goal is that the articles written in Markdown look just like the themes included with Skeleton: `Modern`, `Seaform`, `Rocket` ... and in dark mode too

It would be great if a `mdsvex` based Svelte component could be included in Skeleton that applies the current theme out of the box.

I close the issue and start studying

Again. Thanks Chris!!

**Comment by endigo9740** [comment]
Glad to help. We're available here or on Discord if you need any further help. But general idea is I'd work down from the top:

1. Create your theme to cover the base styles throughout the project
2. Feel free to customize the theme code directly if the generator isn't flexible enough. See our preset source code for examples of this
3. With the foundation established, adjust global styles as needed per my example
4. Then handle more localized changes locally as needed within either specific selectors or locally within a route file

Also note we've been gathering ideas for additional "deep dive" tutorial posts on our blog. This might be a great subject to cover in a future post. So keep an eye for that!
