### ISSUE TITLE
`required` attribute not working in prompt modals

### ISSUE THREAD

**Issue by leranjun** [skeletonlabs/skeleton#699]
### Current Behavior

The `required` attribute on the text input element in prompt modals is not being enforced.

### Steps To Reproduce

1. Go to the [demo page](https://www.skeleton.dev/utilities/modals) and open a "Prompt" modal.
2. Delete everything in the text input and submit.
3. Modal closes despite having 	`required` set.

### Anything else?

https://github.com/skeletonlabs/skeleton/blob/d8a4115188af48aefef11e90f347eee813ee06cc/src/lib/utilities/Modal/Modal.svelte#L174-L181

L176 perhaps needs to be wrapped in a form.

By the way, is it a good idea to submit on enter? It feels more intuitive, but I'm not sure if it fails to comply with accessibility standards.

**Comment by endigo9740** [comment]
FYI I went about this a little bit different than your suggestion. Instead of trying to make it a proper form, I just made it so the submit button is set to disabled if the value is not present. This provides the desired result.

`<button class="btn {buttonPositive}" on:click={onPromptSubmit} disabled={!promptValue}>{buttonTextSubmit}</button>`
