### ISSUE TITLE
Mismatch in Theme Generator's color

### ISSUE THREAD

**Issue by risalfajar** [skeletonlabs/skeleton#739]
### Current Behavior

![image](https://user-images.githubusercontent.com/28381124/209426314-063da0ba-b40e-49f5-b9ba-3e4ce208580c.png)

When I put a hex value in one of the inputs, I expect the value to appear in the 500 variant of the color. But it don't.
For example, when I put `#6366f1` in the primary field, the `primary 500` should be `#6366f1`, but in reality it is `#1A16D8`. I also can't find `#6366f1` in any of the generated colors.

### Steps To Reproduce

1. Open [Theme Generator](https://www.skeleton.dev/guides/themes/generator)
2. Put a Hex value in one of the field
3. Check the generated colors hex value

### Anything else?

This [Pallete Generator](https://www.tints.dev/blue/0A2749) recommended by Skeleton works as intended:
![image](https://user-images.githubusercontent.com/28381124/209426421-30942cf2-e5e0-4781-a9fe-96092d3750a4.png)

**Comment by endigo9740** [comment]
There's a major overhaul to the theme system coming in the next release. I'd recommend reading through this post if you're curious to see what's coming:
https://github.com/skeletonlabs/skeleton/issues/598

Likewise you can test the new generator here:
https://dev.skeleton.dev/guides/themes/generator

**Comment by risalfajar** [comment]
Thanks, the new generator is amazing!

Just want to add that there are still a bit of mismatch on some random colors, it isn't much, but maybe you want to take a look.
![image](https://user-images.githubusercontent.com/28381124/209467130-c2d39098-cd5b-4aeb-9e62-8b0b3f9fa405.png)
![image](https://user-images.githubusercontent.com/28381124/209467254-56c0d817-5415-48f5-817b-1d639499739a.png)

**Comment by endigo9740** [comment]
@risalfajar This may be an unfortunate side effect of Tailwind requiring RGB colors instead of hex. I don't know that they'll always translate 1:1.

Here's roughly house the script works:

1. The hex color is pass through to shade 500 right away, with the hex and "on" (text/fill) color generated:

https://github.com/skeletonlabs/skeleton/blob/dev/src/docs/DocsThemer/colors.ts#L96

2. You can see how the RGB color is generated here:

https://github.com/skeletonlabs/skeleton/blob/dev/src/docs/DocsThemer/colors.ts#L36

This space separate RGB value is the format Tailwind recommends in their docs for the CSS properties, so that Tailwind can implement the Alpha transparency:

https://tailwindcss.com/docs/customizing-colors#using-css-variables

3. We then generate the theme CSS, which is a set of CSS properties. Each color looks like this:

```css
--color-primary-500: 15 186 129; 
```

4. We then apply this stylesheet to the document head, which applies the styles for the live preview:

https://github.com/skeletonlabs/skeleton/blob/dev/src/docs/DocsThemer/DocsThemer.svelte#L106

5. Finally, the swatch component then displays the generated CSS value for that row/shade:

https://github.com/skeletonlabs/skeleton/blob/dev/src/docs/DocsThemer/Swatch.svelte#L18

So believe if an issue is occurring it's at step 2 above. If you know of any solution for more accurate RGB conversion please et me know. Otherwise, this may not possible to solve. It may not be a issue with the generator, but rather, just the nature of converting hex -> rgb to satisfy Tailwind's requirements here.

Make sense?

**Comment by endigo9740** [comment]
FYI I've reopened this ticket so we can look into the RGB conversion a bit more.

**Comment by endigo9740** [comment]
@risalfajar I've done a bit of research on this today. So here's a couple posts that provide some useful insights to this topic.

- https://graphicdesign.stackexchange.com/questions/127480/is-there-a-loss-of-quality-when-converting-rgb-to-hex
- https://graphicdesign.stackexchange.com/questions/110106/should-a-hex-value-match-its-rgb-value-in-a-brand-guideline-document

Essentially hex colors are hexadecimal representations of values. They don't inherently have anything to do with color. It's just a compact format to store these values. Whereas RGB and RGBA are more purpose-built to describe specific colors. So the problem seems to lie in the conversion process and more specifically, the potential for rounding errors.

Take this for example:

```
Hex: #00E06C

R: 00 = 0
G: E0 = 224
B: 6C = 108
```

Here the three sets of hex pairs must be translated to a scale of 0-255 for RGB. These don't always map out 1:1. Rounding errors can occur, which explains why this only occurs sometimes. BUT, here's the important part. The rounding error doesn't really impact the final display by an amount that most users should be able to perceive:

For comparison, here's the two values from your provided screenshots above:

![image](https://user-images.githubusercontent.com/1509726/209573663-526baf17-d171-463a-939d-0fe04d0ff8e2.png)

And here's the values visually compared in Sketch, a UI/design focused Mac tool (I'd expect similar results in Photoshop):

![Screen Shot 2022-12-26 at 11 54 52 AM](https://user-images.githubusercontent.com/1509726/209573299-c7a8e0fb-95b4-4cf9-ac96-9f2febe8150c.png)

Can you tell the difference between the two? Because I can't, and I've worked for nearly 20 years as a design. In fact I handled color calibration for a photography studio in the past. My eyes and my equipment are well tuned for this sort of thing.

I'm not saying the ARE the same, and I am annoyed as well that they are not 1:1. But this is so approximate that I don't think anyone users will notice anything without pulling out a color picker like you and your designer.

What I will do is look into implementing a warning message about this issue, and encourage folks to manually hand curate their palettes if the results of our generator are not to their liking. Web-based tooling may not be the best solution to to this though, given the widely know issues with floating point precision errors in Javascript in general.

**Comment by risalfajar** [comment]
Thanks for giving a very detail explanation. I just found that [tints.dev](https://www.tints.dev/green/22C55E) also suffer the same issue on some colors. And using different color picker (Chrome Extension and Linux app) results in different mismatch values.

I agree with you, the difference is not much for eyes to see. I think this is a very low priority problem. You can even close the issue if you want. I've decided to just go with the generator. 😅

I myself not very experienced in this. So sorry I can't help. And thanks once again!

**Comment by endigo9740** [comment]
No worries, glad to help. Thank you for making me aware of the issue, it's was easy to miss! But yeah, unfortunately I'm not sure there's a solution with automated conversion using Javascript.

One of our core team members @ryceg mentioned last night that he's interested in exploring Hex -> HSL as it appears Tailwind now supports this (it's a recent addition). It will most likely be subject to the same issue, but it's at least another avenue to explore. So fingers crossed!

For now I'll go ahead and close this out as, like you, I feel our current solution is good enough. Hopefully others will agree :)
