### ISSUE TITLE
Vite/Tailwind do not like font imports at the bottom of theme files

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#770]
### Current Behavior

![Screen Shot 2023-01-05 at 11 47 25 AM](https://user-images.githubusercontent.com/1509726/210846815-35fc95d5-af84-41ac-b114-0e084757f29f.png)

Functionally this works, but Vite/Tailwind are not happy. This was a recent change by @AdrianGonz97. We'll aim to revert and silence this warning.

**Comment by endigo9740** [comment]
@AdrianGonz97 I'm going to plan to set aside some time Monday to review this myself if you don't get to it sooner.

We'll need to prioritize the end user experience (devs) over our doc site for now. Most devs won't be doing theme switching and this warning message will make folks think something is broken. Then we'll have support messages out the wazoo!

I'm fine with a duct tape fix if it gets us through the release on Tuesday. Then we can revisit a more permenant change after that if need be.

**Comment by AdrianGonz97** [comment]
@endigo9740 
The duct tape fix would be to do what I suggested a couple of days ago which would be to create a second file for each theme and import it into the exported theme file. I'll close my current PR for now (since I don't necessarily want to lose that progress) and make a new one for this temporary fix.
