### ISSUE TITLE
Menu z-index when in table

### ISSUE THREAD

**Issue by deheldenbv** [skeletonlabs/skeleton#779]
### Current Behavior

When a menu is opened from a button in a tablerow it is being clipped by the table itself.

### Steps To Reproduce

```
<div class="table-container">
	<table class="table">
		<tbody>
			<tr class="table-row">
				<td width={40}>
					<span class="relative">
						<button class="btn text-tertiary-500" use:menu={{menu: "amenu", fixed: true}}>
							<svg
								xmlns="http://www.w3.org/2000/svg"
								fill="none"
								viewBox="0 0 24 24"
								stroke-width="2"
								stroke="currentColor"
								class="w-6 h-6"
							>
								<path
									stroke-linecap="round"
									stroke-linejoin="round"
									d="M12 6.75a.75.75 0 110-1.5.75.75 0 010 1.5zM12 12.75a.75.75 0 110-1.5.75.75 0 010 1.5zM12 18.75a.75.75 0 110-1.5.75.75 0 010 1.5z"
								/>
							</svg>
						</button>
						<nav
							class="menu-tr -mt-8 mr-6 list-nav card p-4 w-52 shadow-xl text-right "
							data-menu="amenu"
						>
							<ul>
								<li>
									<button on:click={() => {}} class="w-full option btn-sm">Edit</button>
								</li>
								<li>
									<button on:click={() => {}} class="w-full option btn-sm">Delete</button>
								</li>
							</ul>
						</nav>
					</span>
				</td>
			</tr>
		</tbody>
	</table>
</div>
```

**Comment by endigo9740** [comment]
Hmm that's an odd one. The table shouldn't have a z-index by default. Are you sure it's not an overflow issue? To test you can try adjusting the z-index. Here's how they're set in the source:
https://github.com/skeletonlabs/skeleton/blob/master/src/lib/styles/elements/menus.css#L4

I'm away from my workstation today, so if you want to test this add the following to your `/src/app.postcss` stylesheet:

`[data-menu] { @apply absolute z-50 hidden; }`

Or use an arbitrary value like `z-[999]`,

Menus in tables are kind of an odd use case we hadn't really accounted for. The way overlays work with CSS is you need a wrapping relatively position element. I see you're using a span for this, but try removing the span and moving the relative class up higher - say to the `<tr> or `<table>` elements. It may be positioned weird if you do, but that'll help signal if it's an overflow issue clipping the menu.

Otherwise I might suggest an alternative way to present the info for now, such as a native select input (the browser handles the layer for those), a slide our drawer, or a custom modal. It may take adjustments to the table styles themselves to allow this to work.

**Comment by endigo9740** [comment]
Closing this out for two reasons:

1. No response in several days
2. Alternatives were provided

I don't believe this is a use case we're going to spend time to support right now. If we see this request come up repeatedly in the future we'll devote some time to this then.

Thanks.
