### ISSUE TITLE
Complex select elements

### ISSUE THREAD

**Issue by OlmoDalco** [skeletonlabs/skeleton#901]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Enable complex select elements via [svelte-select](https://github.com/rob-balfre/svelte-select). 
Can be achieved by exporting the no-sytle _Component_ and applying skeleton theme to svelte-select classes.   ![image](https://media.giphy.com/media/Y79mKXp8SaYMZq6rFp/giphy.gif)

### What type of pull request would this be?

New Feature

**Comment by OlmoDalco** [comment]
@endigo9740 

Any suggestions how to create long select list requiring search/autocomplete and loading options from the backend as well as custom components for rendering options and the current selection? This is one of the main things keeping us from switching to skeleton and i am not completely sure how the menu or current listbox component would help with any of these requirements.

**Comment by endigo9740** [comment]
I saw you posted in the Autocomplete ticket here, so I know you're aware that's in the works. It's coming as soon as we have a chance, but no set ETA at this moment. I'd suggest subscribing to that ticket so you're notified when updates occur:
https://github.com/skeletonlabs/skeleton/issues/377

You might take a look at how we setup our custom search on the Skeleton doc site:
https://github.com/skeletonlabs/skeleton/blob/dev/src/docs/DocsSearch/DocsSearch.svelte

It's in a dialog, rather than a menu, but a lot of the same concepts will apply.

Loading data from the backend would involve using Load functions and other feature of SvelteKit, so that's out of scope for Skeleton. But I can recommend these videos by Joy of Coding or Huntabyte on the topic:
- https://www.youtube.com/watch?v=rsmLu5nmh4g&t=163s
- https://www.youtube.com/watch?v=EQy-AYhZIlE

**Comment by endigo9740** [comment]
> am not completely sure how the menu or current listbox component would help with any of these requirements.

Here's a quick visualization on how you could combine these Skeleton features to build a Combobox (the term for what you're after):

[Screenshot 2023-01-30 at 11 54 54 AM](https://user-images.githubusercontent.com/1509726/215555653-bf3c1087-ff59-46c6-bdcf-cdc70f750371.png)

- Green: a Skeleton button with a downward pointing caret. This would be your Menu trigger
- Red: the Menu would act as your popup container
- Blue: a listbox with multiple options for selection

Here's the docs for each of those:
https://www.skeleton.dev/elements/buttons
https://www.skeleton.dev/utilities/menus
https://www.skeleton.dev/components/listboxes

Though as noted above the format for implementing Listboxes will change in next week's release, so FYI on that. Remember we're still in pre-release status, so things are changing rapidly.
