### ISSUE TITLE
LightSwitch does not correctly set class attribute if ssr = false

### ISSUE THREAD

**Issue by dldx** [skeletonlabs/skeleton#905]
### Current Behavior

The LightSwitch component does not correctly set the dark mode class if server side rendering is disabled on a page. This is because the component currently relies on populating a `<script>` tag in the `<head>` which only runs on initial page load. If server side rendering is false, this script tag doesn't exist until the LightSwitch is toggled off and on again.

Example of LightSwitch component when dark mode is set and page refreshed, while `ssr = false`:
![image](https://user-images.githubusercontent.com/107700/215587628-767b60d5-9e47-4508-b8f6-2e426be93184.png)

Example when `ssr = true`:
![image](https://user-images.githubusercontent.com/107700/215587541-30551ce6-fec7-4ccc-8409-07bf36185b9e.png)

In my opinion, LightSwitch should not need to depend on serverside rendering to function.

Thanks to the developers for this amazing project!

### Steps To Reproduce

1. Use LightSwitch component as described in the documentation
2. Add `export const ssr = false` to the page you are loading
3. Note that dark mode value is not set when you refresh the page.

**Comment by endigo9740** [comment]
Thanks for the feedback @dldx. We certainly didn't intend for these to be SSR-only. But FYI we do have some big changes planned for this feature in the near future:

- https://github.com/skeletonlabs/skeleton/issues/737

We'll take your feedback here into account when updating that. Thanks for your submission.

**Comment by endigo9740** [comment]
This may be solved as part of: https://github.com/skeletonlabs/skeleton/issues/922

Further testing may be required. If you do not have access to test the active PR, then I suggest waiting for next week's release. Test the production version when updated, then report back if issues are still present.

For now keep all additional comments limited to the ticket linked above.

**Comment by endigo9740** [comment]
The issue has been confirmed to still be present. Reopening this for now.

**Comment by jcoble** [comment]
I found a couple workarounds for this in order to have ssr = false and have the LightSwitch still work on page refreshes.  Like didx said, on page load, the setInitialClassState doesn't get called.  I do see that since his original post, it was called setColorScheme and now is setInitialClassState and is actually being inserted into the head even with SSR = false.  But, the function is not being called.  It looks like it wasn't being written to the head if ssr was false before, until it was toggled.

So, simplest solution I found was to just import setInitialClassState into your main layout.svelte and then just call it from there.

![image](https://user-images.githubusercontent.com/17329655/221385131-d683998d-c557-481d-9d6a-32b733e1916f.png)

[https://www.skeleton.dev/utilities/lightswitches](url)
This is in the docs except that it's for custom switches and functionality.  Maybe if the docs had a disclaimer that if the user wants to turn off ssr, then they need to call this function in the main layout? 

I also had just copied and pasted the code in the function, straight in the app.html head.  It works just as well, but there will then be 2 setInitialClassState functions.  Another is created from the LightSwitch itself, but never gets called.  Having 2 of those functions doesn't effect anything, but I think it's probably cleaner the other way.

I tested through both my app and a clean install of an app from the CLI and didn't find any issues with this.  I'm no sveltekit expert by any means, so someone more versed might want to make sure my logic isn't flawed.

**Comment by endigo9740** [comment]
After reading the suggestion above I think @jcoble solution may be our best bet for folks running with SSR disabled. So I'm going to recommend a few options here:

1. Consider enabling SSR if possible, honestly it's a good thing if your hosting solutions provides it
2. Use @jcoble suggest if you want to cover the scenario outlined in the original post (SSR false)
3. Consider using the OS preference or other helper methods provided on the Lightswitch documentation page if you need to roll a custom solution here
4. Consider pinning your app to use only light or dark mode if you're disabling SSR. This can be done by adding or removing the `.dark` class to your app.html `<html>` element.

Not every suggestion may be ideal for every use case, but given what I understand of the situation these will be our recommendations for the time being.

**Comment by MrVauxs** [comment]
I will note that even without `ssr = false`, this bug appeared in a GitHub Pages hosted, adapter-static app.
Nevertheless, jcoble's solution works.

**Comment by e253** [comment]
I had this issue making an SPA. Calling `setInitialState()` fixed for me. Not too bad, but I would add to docs. Love this project!

**Comment by nasheomirro** [comment]
+1 in adding this to the docs, took me a few to find this issue.

**Comment by endigo9740** [comment]
Folks, we can't monitor every single closed issue in the hopes someone has a valuable suggestion. Start a new issue or send a PR if you want to see this change implemented.
