### ISSUE TITLE
Rounded borders with `input-group` look weird in v0.124.2

### ISSUE THREAD

**Issue by AgarwalPragy** [skeletonlabs/skeleton#942]
### Current Behavior

This is what the following input-group looks like
```html
<div class="input-group grid-cols-[auto_1fr_auto]">
    <div class="input-group-shim">
      <Icon icon="ph:password" class="h-5 w-5" aria-hidden="true" />
    </div>
    <label class="sr-only" for="new-password">Choose a strong, secure password</label>
    <input
      class="input"
      type="password"
      name="password"
      id="new-password"
      autocomplete="new-password"
      required
      placeholder="A strong, secure password"
    />
</div>
```

<img width="412" alt="image" src="https://user-images.githubusercontent.com/7423639/217647421-c6b67879-4d00-4509-9647-9131f2af9bd8.png">

On adding a state variant, the border inside the input-group is no longer vertical if the theme has rounded borders

```html
<div class="input-group grid-cols-[auto_1fr_auto]">
    <div class="input-group-shim">
      <Icon icon="ph:password" class="h-5 w-5" aria-hidden="true" />
    </div>
    <label class="sr-only" for="new-password">Choose a strong, secure password</label>
    <input
      class="input input-success"
      type="password"
      name="password"
      id="new-password"
      autocomplete="new-password"
      required
      placeholder="A strong, secure password"
    />
</div>
```
<img width="400" alt="image" src="https://user-images.githubusercontent.com/7423639/217648199-674fab1b-382c-4beb-8b20-809d06539c2e.png">

Note that the `input-group-shim` uses a vertical border while the `input` uses a rounded border

<img width="128" alt="image" src="https://user-images.githubusercontent.com/7423639/217648378-8e4b4a77-0ae2-4b58-adce-8037a6fb07bb.png">

**Comment by endigo9740** [comment]
Ahh interesting that's making it down to the input - ok we'll take a look. Thanks!

**Comment by endigo9740** [comment]
@AgarwalPragy ok, so I see the issue here, you've got a small mistake. It looks like you've applied `.input` to the `<input>` within the group. You actually want to avoid applying `.input` or similar to the child input elements.

Here's what the input regions look like by default, without `.input` applied (note the green):

![Screenshot 2023-02-10 at 11 21 25 AM](https://user-images.githubusercontent.com/1509726/218156435-8f93354e-a5ff-4988-bd81-2114f1830bb8.png)

If I apply the class styles to the input themselves, I end up with:

![Screenshot 2023-02-10 at 11 21 58 AM](https://user-images.githubusercontent.com/1509726/218156515-ecd48b01-36cd-43c2-9197-20c65f89f110.png)

So per your example above:

```html
<div class="input-group grid-cols-[auto_1fr_auto] input-success">
    <div class="input-group-shim">
      <Icon icon="ph:password" class="h-5 w-5" aria-hidden="true" />
    </div>
    <label class="sr-only" for="new-password">Choose a strong, secure password</label>
    <input
      type="password"
      name="password"
      id="new-password"
      autocomplete="new-password"
      required
      placeholder="A strong, secure password"
    />
</div>

```

Will produce:

![Screenshot 2023-02-10 at 11 29 50 AM](https://user-images.githubusercontent.com/1509726/218157392-3fec0fbf-e749-4f00-b39c-37c93c1397a7.png)

While:

```html
<div class="input-group grid-cols-[auto_1fr_auto]">
	<div class="input-group-shim">
            <Icon icon="ph:password" class="h-5 w-5" aria-hidden="true" />
        </div>
	<label class="sr-only" for="new-password">Choose a strong, secure password</label>
	<input
		class="input-success"
		type="password"
		name="password"
		id="new-password"
		autocomplete="new-password"
		required
		placeholder="A strong, secure password"
	/>
</div>
```

Will produce:

![Screenshot 2023-02-10 at 11 30 14 AM](https://user-images.githubusercontent.com/1509726/218157394-9d773491-7d02-47a9-8b54-84dfb8d34931.png)

(note I don't have access to your icon, so I substituted in my screenshots.

**Comment by AgarwalPragy** [comment]
Ah, that makes sense! Thanks :)
