### ISSUE TITLE
Carousel component

### ISSUE THREAD

**Issue by ibilux** [skeletonlabs/skeleton#952]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Hello,
Can we expect a carousel component to slide through multiple elements and images using custom controls, indicators, intervals, and options ?

### What type of pull request would this be?

New Feature

### Any links to similar examples or other references we should review?

https://daisyui.com/components/carousel

https://flowbite-svelte.com/components/carousel/

**Comment by endigo9740** [comment]
Noting this for later:
https://www.smashingmagazine.com/2023/02/guide-building-accessible-carousels/

**Comment by Mahmoud-zino** [comment]
I would like to work on this component.

**Comment by endigo9740** [comment]
Assigned it @Mahmoud-zino, thanks! We've been very leery of having a carousel in Skeleton because they are typically not great UI. So make sure you read that Smashing Magazine article in full please. As well as any others you can find:
https://www.smashingmagazine.com/2022/04/designing-better-carousel-ux/

There's plenty of information on the risks:
https://thegood.com/insights/ecommerce-image-carousels/

**Comment by tizu69** [comment]
Why not just use tailwind to implement this yourself?

https://tailwindcss.com/docs/scroll-snap-type

I may not exactly get the feature request, sorry

**Comment by Mahmoud-zino** [comment]
@endigo9740 yeah so after reading the two articles I am really skeptical about Skeleton having its own Carousel.
However, I will implement it with Accessibility as my highest Prio and discuss with you what should be changed and if we would / would not introduce the component.

**Comment by endigo9740** [comment]
@Mahmoud-zino totally fair, and @tizu69 comment is relevant here too - CSS can do some cool snapping stuff these days. Perhaps we treat this as a "Block" feature?

**Comment by Mahmoud-zino** [comment]
@endigo9740 can you elaborate more on the "Block" feature?

**Comment by endigo9740** [comment]
@Mahmoud-zino these are elements created with HTML/Tailwind and perhaps a few simple Skeleton primitive (ex: buttons):
https://dev.skeleton.dev/elements/chat

We have another incoming one for image layouts here:
https://github.com/skeletonlabs/skeleton/pull/1617

Basically little to no JS logic, just providing the structure.

**Comment by Mahmoud-zino** [comment]
@endigo9740 Ah ok now I understand what you mean.
But we will have to define what we want because I am not that creative without tasks 😢 .
Should I just create a snapping-container sort of thing or do you have something else in mind?

I know on weekends you don't have much time for discussions so no rush we can do that another day also. 👍

**Comment by endigo9740** [comment]
We'll circle back this week. No worries!
