### ISSUE TITLE
docs: "Added a !no-underline class to prevent text underlines"

### ISSUE THREAD

**Issue by alexander-mart** [skeletonlabs/skeleton#983]
### Link to the Page

https://www.skeleton.dev/docs/comparisons

### Describe the Issue

```diff
- Added a !no-outline class to prevent text underlines.
+ Added a !no-underline class to prevent text underlines.
```

### Are you able to create a Pull Request with the fix?

Yes

**Comment by endigo9740** [comment]
@alexander-mart can you expand on your issue here? You link to the comparison page but I see no relevance to what you're describing. In fact I can find no instance of `no-outline` in the entirety of the Skeleton project.

**Comment by alexander-mart** [comment]
@endigo9740 It's inside the spoiler: View Flowbite integration mini-guide.

**Comment by alexander-mart** [comment]
@endigo9740 I'm assuming the documentation pages haven't been published to github yet.

**Comment by endigo9740** [comment]
Ahh I see, you're checking against production branch, but this section has been moved and modified on dev branch and is no longer present. That's why I could not find this. The updated section now links directly to our blog post detailing full integration instructions with Flowbite:
https://dev.skeleton.dev/docs/introduction

Expect to see this version of the docs drop with our standard release cycle on Tuesday of this week (US time)

The library and documentations are a combined project within this repository. You can find this new page here:
https://github.com/skeletonlabs/skeleton/blob/dev/src/routes/(inner)/docs/introduction/%2Bpage.svelte#L132

Also be aware we're right in the midst of a major documentation overhaul. A lot of info will be tweaked, adjusted, moved, and various visual changes implemented. You can follow along here:
https://github.com/skeletonlabs/skeleton/issues/783

For now the suggest change is no longer relevant, so I'm going to go ahead and close this out. Thanks though!
